;********Special symbols:  (Please keep the format integrity.)********
;  #-as a newline, In the middle of the string,
;  !-Displayed in red at the CodingList,First char of the string
;  ,-Separator
;  &-Shortcuts delimiter
;  %S,%D-Replace strings and numbers
;  |-Status Bar hint
;*********************************************************************

;****************************Language*********************************
Lang=English
;*********************************************************************

;*****************Translator copyright information********************
;Be displayed in the application
Copyright=Welcome ...#This app is free, you do not need to pay any fees. #My email: snzdl555@gmail.com
;*********************************************************************

;*****************************Coding**********************************
[ICM]
00=Electronic speed limit,OFF,ON

[FRM/BODY]
;12F
00=START&STOP remember the last state,ON,OFF
01=START&STOP default OFF,OFF,ON
02=Stop windows when Opening doors,ON,OFF
03=Stop windows when Opening doors,ON,OFF
04=Turn signal times:
05=Turn on the left fog lights,Not Active,Soft ON,Hard ON
06=Turn on the right fog lights,Not Active,Soft ON,Hard ON
07=Emergency brake open double flash,OFF,ON
08=Ambient Light brightness adjustment:
09=Interior lighting holding time:
10=Interior lighting holding time:
11=Unlock internal light holding time:
12=Unlock internal light holding time:
13=Reversing rear view mirror turn angle:
14=Headlight cleaning,ON,OFF
15=Headlight cleaning interval,Once,Five times,Ten times
16=Headlight cleaning times:
17=Automatically turn off the radio and music,ON,OFF
18=Start car with brake,ON,OFF
19=Brake light flashing,OFF,flaechenvergroesserung,Brake light flashing
20=Brake lights flicker sensitivity,ECE,US,ECE_M_Sport
21=Brake lights flicker sensitivity,ECE,US
22=Folding mirrors delay time:
23=Brake lights flicker sensitivity,ECE,US,ECE_M_Sport
24=Brake lights flicker sensitivity,ECE,US
25=Personality double flash
26=High-beam assistant default ON,OFF,ON
27=Door handle LED ON when reversing,ON,OFF
28=Brake lights flicker sensitivity,ECE,US
29=Turn OFF the headunit,ON,OFF
30=Folding mirrors delay time:
31=1Fog as corners auxiliary lighting:
32=2Automatic Headlamp Leveling System(AHL),OFF,ON
33=2cornering lights,OFF,ON
34=2Left Cornering lights,OFF,ON
35=2Right Cornering lights,OFF,ON
36=2Mapping left output,ON(NSW_L),FL_L,OFF
37=0Mapping right output,ON(NSW_R),FL_R,OFF
EX04=Max value:7
EX05=when the welcome light ON
EX06=when the welcome light ON
EX09=After locking the car
EX10=After locking the car
EX17=After flameout and open the door.
EX19=When the emergency brake
EX20=negative accelerations
EX21=Speed threshold
EX22=Unit 100ms, 0 is no delay
EX23=negative accelerations
EX24=Speed threshold
EX28=Speed threshold
EX29=When flameout and open the door.
EX33=2Prerequisite:AHL ON
[FZD]
00=Locking sound confirm volume
01=Automatic Volume,ON,OFF
02=Buzzer frequency
03=Buzzer Delay
EX01=20:00-8:00 volume will be smaller
[CAS]
00=Remember last start&stop state,ON,OFF
01=Start&stop default OFF,ON,OFF
02=Turn OFF the HeadUnit,ON,OFF
EX02=After flameout and open the door.
[KOMBI]
;760  69
00=GPS time synchronization,ON,OFF
01=Dashboard instantaneous fuel consumption scale,20L/100km,30L/100km
02=Dashboard daytime background color,Orange,gray
03=Dashboard night Background Color,Orange,gray
04=Dashboard daytime luminance value:
05=Dashboard night brightness value:
06=HUD display entertainment,ON,OFF
07=HUD display phone,ON,OFF
08=HUD display phone book,ON,OFF
09=HUD display voice command,ON,OFF
10=HUD display turn signals,ON,OFF
11=Digital speed,ON,OFF
12=Trip computer reset delay (hours)
13=HUD display turn lights
14=Remind when open the door,ON,OFF
15=Fuel alarm km:
16=The second Fuel alarm km:
17=According speed curve to fix speed,ON,OFF
18=HUD display turn lights,ON,OFF
19=HUD display indicators,ON,OFF
20=Dashboard LOGO index number:
21=Display Compass,ON,OFF
22=Display digital odometer,OFF,kmh_mph,mph_kmh,mph_mph,No MPH,No KMH
EX11=BC button to call
EX12=Set to 0 - Instant Reset
EX17=OFF - Show the actual speed
EX20=MAX:15
EX21=Full LCD dashboard applicable
EX22=Latter two only later 005_000_056
[HKL]
00=A-pillar switch operating Power Trunk,OFF,ON
01=FOB to terminate and reverse Power Trunk,OFF,ON
02=FOB and A-pillar matches,OFF,ON
03=A-pillar button to open/close Power Trunk,OFF,ON
04=FOB to close Power Trunk,OFF,ON
[IHKA]
00=Air conditioning switch remember the last state,ON,OFF
01=Air conditioning switch remember the last state,OFF,ON
02=Air-conditioning cycle remember the last state,ON,OFF
03=Air-conditioning cycle remember the last state,OFF,ON
[ACSM]
;9C 9D 147
00=Seatbelt alarm delay
01=Passenger seat belt warning,ON,OFF
02=Driver's seat belt warning,ON,OFF
03=Driver seat belt status display,ON,OFF
04=Passenger seat belt status display,ON,OFF
05=Warning the driver's seat belt is opened,ON,OFF
06=Warning the Passenger seat belt is opened,ON,OFF
07=The initial seat belt warning,ON,OFF
EX00=Unit:seconds, once about 2-3
[CIC/NBT]
00=Lock/unlock Sound confirm checkbox,ON,OFF
01=1Video in motion
02=2Canceling speed lock value:
03=0Activation speed lock vlue:
04=Disclaimer display delay:
05=Reversing video Disclaimer delay:
06=Night Vision Disclaimer delay:
07=Version View menu,ON,OFF
08=Show engine power and torque,ON,OFF
09=iPhone Ringing as Bluetooth ringing,ON,OFF
10=NAVI Gas station reminders,ON,OFF
11=USB can import Geocoding,ON,OFF
12=Navigate add location menu,OFF,ON
13=NAVI Points of Interest Online Search,browser,nativ
14=1USB Play Video,OFF,1st USB,2nd USB,Both USB
15=2Xvid Video Decoder,OFF,ON
16=0VCD and SVCD video support,OFF,ON
17=Save video files to the Internal memory,OFF,ON
18=Navigation route preview,ON,OFF
19=Navigation Route preview button,OFF,ON
20=Navigation voice male/female voices,ON,OFF
21=Screen type of display,NarrowScreen,widescreen,flap,schmales_flap
22=Reversing analog image display,Vertical,Transverse
23=Daytime Running Light Checkbox,OFF,ON,Standard
24=Show Ambient Light adjustment,OFF,ON
25=Disable UPnP/WLAN Audio,ON,OFF
26=Disable UPnP/WLAN video,ON,OFF
27=Get video stream from WLAN,OFF,ON
28=Wifi switch,ON,OFF
29=WLAN connection mode,AP,Client,Both,WIFI_Direct
30=WIFI connection strength,InCar,OutDoor
31=M digital speed display,ON,OFF
32=M-HUD,ON,OFF
33=HeadUnit startup screen,Default,M,ALPINA,BMW I,bmw i,Angel,Like default,bmw,Orange grid BMW,Christmas
34=HUD show turn signals checkbox,ON,OFF
35=Oil level menu,ON,OFF
36=Release the handbrake termination Video,OFF,ON
37=Volume bar,Show,NoShow
38=Volume bar fade ended prematurely,ON,OFF
39=The volume bar display low priority,ON,OFF
40=1The controller can touch,OFF,ON
41=2Touch operation Interactive map,ON,OFF
42=2Touch for spelling,ON,OFF
43=2Touch for browser,ON,OFF
44=0High-speed lock-touch,ON,OFF
45=Compass,ON,OFF
46=Torque and xDrive status MENU,Show,NoShow
47=3D map scroll,ON,OFF
48=1Digital tire pressure monitoring system,ON,OFF
49=0Tire pressure monitoring-vehicle safety,ON,OFF
50=Head Up Display(HUD),Installed,NoInstalled
51=Show B&&O Sound menu,kein_menue,keine_insz,nur_lichtinsz,volle_insz
52=In the sound menu show Logic7_Logo,ON,OFF
53=EQ Data Definition must be loaded,stereo,hifi,tophifi,individual_sound,hk_surroundsound,highpremium,hifi_system_harmankardon
54=1Bluetooth music
55=0Apple devices Bluetooth audio streaming,ON,OFF
56=2Bluetooth audio streaming controller,ON,OFF
57=2Bluetooth audio streaming controller,ON,OFF
58=M color scheme,ON,OFF
EX00=Settings - Door Locks Activate Use
EX01=Set All to 255
EX02=Set to 255 is not locked
EX03=Set to 255 is not locked
EX04=Set to 0 is not show
EX05=Set to 0 is not show
EX06=Set to 0 is not show
EX09=Only iPhone
EX14=Choose which USB to play video
EX15=support MP4
EX16=support MPEG
EX34=And in related options with KOMBI
EX38=When there are other operations
EX39=Lower priority than Warning
EX46=Show compass
EX48=!Must have the relevant hardware
EX50=Activate the installation of HUD
EX56=A2DP & AVRCP 1.3
EX57=AVRCP1.4 Includ browsing
[CMB_MEDIA]
00=Speech Recognition,ON,OFF
01=Use Mobile phone ringtones,OFF,ON
02=Choose ringtones,RING_TONE1,RING_TONE2,RING_TONE3
EX01=Only iPhone

;***************************Application*******************************
[APP]
BT_TOOLS=&Tools
BT_FILTER=&Filter
BT_CANCEL=&Cancel
BT_OK=&OK
BT_Close=&Close
BT_Copy=&Copy to Clipboard
BT_HIDELIST=Coding List
BT_SCANCAR=&1.DetectCar
BT_SCANCAR_HINT=|Automatically detect car information for connecting.
BT_LINKCAR=&2.Connect
BT_LINKCAR_HINT=|Connection to the car.
BT_UNLINK=&Disconn
BT_UNLINK_HINT=|Disconnect.
BT_LINKNAT=&Connect
BT_LINKNAT_HINT=|Connection with ICOM or NAT.
BT_READECUS=&3.Get ECUs List
BT_READECUS_HINT=|Get all modules information of the car.
BT_SAVEECUS=&Save
BT_SAVEECUS_HINT=|Save the module information into a text file.
BT_ABOUT=&About
BT_ABOUT_HINT=|About this app.
BT_OPTION=&Option
BT_OPTION_HINT=|Setting Options.
BT_QUIT=&Exit
BT_QUIT_HINT=Exit Application.
BT_READ=&4.Read
BT_READ_HINT=|Reads the data of the selected module.
BT_WRITE=&5.Write
BT_WRITE_HINT=|Put coding write-car.
BT_BACK=&Backup
BT_BACK_HINT=|The original data backup(App will automatically backup).
BT_RECOVERY=&Restore
BT_RECOVERY=|Coding return to backup status.
BT_LOADFSC=&Load FSC
BT_LOADFSC_HINT=|Load FSC file, the file format can be binary or hexadecimal or XML.
BT_SAVEFSC=&Save as
BT_SAVEFSC_HINT=|The FSC in the editbox save as a binary or hexadecimal format file.
BT_REFRESH=&Refresh
BT_REFRESH_HINT=|Reread the FSC list in the Headunit.
BT_GETFSC=&Get FSC
BT_GETFSC_HINT=|Get the selected FSC from headunit.
BT_BAKFSC=&Backup All FSC
BT_BAKFSC_HINT=|Backup all FSC within the Headunit.
BT_GEN=&Generate
BT_PUTFSC=&Write to car
BT_PUTFSC_HINT=|Put the activation code to headunit. when upgrade map, do not need to be input manually.
BT_GETFMAP=Get from &map
BT_GETFMAP_HINT=|Get the country code and version number from the map file.
BT_GETFXML=Get from &lookup.xml

LB_Country=Country:
LB_VERCODE=VerCode:
LB_VIN=VIN:
LB_WARNING=WARNING:
LB_FSCNOTE=Note:Generator not my app,It simply calls,thank the original author!
LB_WAR_TIP=Write failed will cause the module to disability or does not work!#Please strictly do the following:#  1, The car must be ACC ON.#  2, Turn off air conditioning and other high-power module.#  3, Start the car, but must be turned off when coding CAS / BODY module.#  4, Do not operating car when writing.#  5, Ensure that the connection will not be interrupted.#  6, Should it fail, please click the restore button to fix.
LB_BAKNOTE=    If the first read, for safety reasons, App will automatically backup it.#Backup files are stored in the app directory,the subdirectory named with VIN.#Be sure to retain this directory and files,##    Click the "Restore" button to restore this backup data, If you need.
LB_IP=Scan IP:
LB_LINKPORT=Link Port:
LB_SCANPORT=Scan Port:
LB_BAKTIT=Select a file to restore:
LB_HIDELISTTIP=Options vary by car.
LB_SCANING=Detecting the car, please wait ....
LB_SCANTIP=1.The car must be ACC ON.#2.IP address set to automatically get.#3.Firewall does not prohibit to access the network.
LB_ENTER=Enter Key#To Confirm
LB_IMPORTANT=IMPORTANT:
LB_CDATE=Creation date:
LB_ICOM=    Get ICOM's IP and port (like: 169.254.92.38:50160),And input in the edit box.

MI_ECU_DATE=Read ECU Manufacturing Date
MI_ECU_PROG=Read Programming Counter
MI_ECU_VOLT=Detecting voltage
MI_CAR_STEP=Integration step
MI_ECU_CPS=Read CPS
MI_ECU_SVK1=Read Current SVK
MI_ECU_SVK2=Read System Supplier SVK
MI_ECU_SVK3=Read Plant SVK
MI_SVK_BAK1=Read Backup SVK 1
MI_SVK_BAK2=Read Backup SVK 2
MI_SVK_BAK3=Read Backup SVK 3
MI_ECU_DTC=Clear Selected ECU's DTC
MI_ALL_DTC=Clear all DTC
MI_ECU_RE=Restart ECU
MI_GEARBOX=Reset Transmission adaptation values(Driving Habits Memory)
MI_GETGEARBOX=Display Transmission adaptation values
MI_DATETIME=Synchronize the date and time to KOMBI

CH_NONEXT=Do not show again
CH_AutoDetect=Automatic scan car after startup.
CH_AutoLink=Automatically connect car.
CH_AutoRead=Automatically get ECUs list.
CH_AUTOSETTIME=Auto time synchronization after coding KOMBI

GB_CAROPTION=Car
GB_SYSOPTION=System
GB_ECUS=ECUs
GB_CODE=Coding

PA_WAIT=Communicating, please wait ...

LV_BAK=Backup Files,Backup Date
LV_FSC=Number,Index,Status

ListView_HINT=Blue has hidden features,if it is red color,please contact me to upgrade.
HideView_HINT=Set it as required and written to the car go into effect.

ST_TIMEOUT=Timeout!
ST_GETPRESSURES=Get Clutch fill pressures...
ST_GETFILLTIME=Get Rapid fill times...
ST_ADAP=Clutch fill pressures:#   Clutch A: %D.0 mbar#   Clutch B: %D.0 mbar#   Clutch C: %D.0 mbar#   Clutch D: %D.0 mbar#   Clutch E: %D.0 mbar##Rapid fill times:#   Clutch A: %D.0 ms#   Clutch B: %D.0 ms#   Clutch C: %D.0 ms#   Clutch D: %D.0 ms#   Clutch E: %D.0 ms  
ST_GENFAIL=Calculate failed!
ST_SELTYPE=Please select the headunit type first.
ST_MAPINFO=Country Code:%S Ver Code:%S
ST_FSCEXE=Cannot call generator, the generator does not exist.
ST_FORMATERR=File format error!
ST_BAKFSC=Backup %S:
ST_BAKEND=End Backup...
ST_NOBAKFSC=FSC Backup Failed!#Click Refresh button and try again.
ST_FSCVIN=Get FSC VIN...
ST_WRCODE=Write activation code...
ST_LOWCODE=The Activation code lower than map version
ST_WRCODEERR=Write Activation code failed,pls try again...
ST_CPSERR=VIN format error, can not continue.
ST_STEP_CUR=Current:%S-%d-%d-%d
ST_STEP_LAS=Last:%S-%d-%d-%d
ST_STEP_SHI=Shipment:%S-%d-%d-%d
ST_SET_EXT_DS=Set Extended Diagnostic Session...
ST_READ_FTP=Read Flash Timing Parameter...
ST_READ_ADS=Read Active Diagnostic Session...
ST_SDS=Set Default Session...
ST_SRESET=Sending restart command...
ST_WAITRE=Waiting for the modules to restart...
ST_TESTM=Final mission testing...
ST_MISSOK=Mission completed...
ST_MISSTER=Mission Terminated...
ST_NOP=Clear execution state...
ST_REDY=Prepare vehicle coding tasks...
ST_SVK=Getting SVK...
ST_SAR=Security access request...
ST_ACCVER=Access verification...
ST_ACCVERERR=Access verification failed!(%S)
ST_SVF_MT=Signature verification failed(%S), Mission termination...
ST_TRYLATER=Unable to secure access, please try again later ...
ST_FTRSA=Request secure access failed...
ST_WRITING=Writing...
ST_WCPS=Writing CPS...
ST_VWD=Verify written data...
ST_CHECKSI=Verify the signature...
ST_GET_CAFD=Get [%S] CAFD information...
ST_CHECK_V=[%S]Detected voltage:%S V.
ST_CHECKV=Detecting car voltage...
ST_CHECKVERR=Unable to detect voltage information,#Ensure the car voltage sufficient and stable!#Continue to write it?
ST_V_LOW=Detection voltage is almost critical point,#In order to ensure safe when writing,#Please write after charging.
ST_CAS=The current code for a starting system control unit (%S).Please turn off the engine continues ...
ST_PROGCOUNT=ECU(%S)Programming Counter:%D Max Value:%D...
ST_NOINFO=This information is not recorded..
ST_MODEDATE=ECU(%S)Manufacturing Date:%S-%S-%S
ST_CLEAR_DTC=ECU:%S DTC Cleared...
ST_SVFAIL=Signature verification failed, mission failed.
ST_KEYFAIL=Key verification failed, abort...
ST_WRITEFAIL=Write failed!#click the Restore button to restore...
ST_NOTRECVCOD=The ECU cannot receive coding tasks,#Please try again later ...
ST_TIMEINVA=Time-domain state is invalid,#please try again later...
ST_WRITETIMEOUT=Response Timeout, please try again...
ST_VIN_FAIL=Check failed [%S] ...
ST_DESKTOP=Software located on the desktop.#Because the software will generate the necessary directories and files,#And automatically backs up the car's original data,#Recommend copying the software in a dedicated directory.#Still run the program now?
ST_SCAN_CAR=Detecting car...
ST_SCANED=Please connect after detect car ...
ST_RELINK=To reconnect, disconnect the current connection first.
ST_LINKING=Connecting ...
ST_LINKSER=Connecting service ...
ST_GETVIN=Getting VIN...
ST_HAND=Handshaking...
ST_UNLINK=Disconnected...
ST_COM_WAIT=Previous command is not finished, please wait ...
ST_GETECU=Getting car's ECUs...
ST_UPDATE=Part of the data need update, please contact me...
ST_SELECU=Please choose an ECU to read ...
ST_NOSUP=Does not support this module...
ST_CODINST=Coded the instrument panel data, maintenance, time and other information will be lost!#Still code it?
ST_NODATA=The current version is no this ECU data ...
ST_UPDATE=Incomplete data, please upgrade...
ST_READCODE=Reading...
ST_NEEDUP=Incorrect data, pls update data ...
ST_DATERR=Incorrect data, could not be completed ...
ST_CHECK=Data integrity checking...
ST_CHECKERR=Data validation fails, do not write to...
ST_WRIT=Changes take effect after writing.
ST_READFIRST=Please read first...
ST_AUTOBAK=Automatic backup data...
ST_BACKUP=Backup data...
ST_OVERBAK=Backup already exists, whether to overwrite backup?
ST_BAKERR=Critical error:#Unable to backup data, the backup operation is very important!#Check and eliminate the cause of this error!
ST_INPUTERR=Incorrect value is entered! Modification fails...
ST_OUTRANGE=Value out range, it has been intercepted...
ST_NOKEY=Get key data error!(%S)
ST_BAKCON=Confirm the selected ECU return to backup status?
ST_CLEARDTC=Confirm Clear to selected ECU's DTC?
ST_ALLDTC=Confirm Clear all DTC?
ST_CONRESTART=Confirm restart to selected ECU?
ST_SELAECU=Please choose an ECU to restore...
ST_BACKMODIED=Backup file has been modified, cannot be restored ...
ST_NOSAVE=Nothing to save....
ST_NOCOMP=Not completed, so stay tuned ....^_^
ST_CODIHKA=Some models car can not turn off air conditioning when after code.#This is completely normal phenomenon, #it can be restored after running for some times.