;********Special symbols:  (Please keep the format integrity.)********
;  #-as a newline, In the middle of the string,
;  !-Displayed in red at the CodingList,First char of the string
;  ,-Separator
;  &-Shortcuts delimiter
;  %S,%D-Replace strings and numbers
;  |-Status Bar hint
;*********************************************************************

;****************************Language*********************************
Lang=Italiano
;*********************************************************************
Translate= bmwretrofit.it
;*****************Translator copyright information********************
;Be displayed in the application
Copyright=Benvenuto ...#Questa applicazione e' gratuita, non dovete pagare nulla. #Mia email: snzdl555@gmail.com
;*********************************************************************

;*****************************Coding**********************************
[ICM]
00=Electronic speed limit,OFF,ON

[FRM/BODY]
;12F
00=START&STOP remember the last state,ON,OFF
01=START&STOP default OFF,OFF,ON
02=Stop windows when Opening doors,ON,OFF
03=Stop windows when Opening doors,ON,OFF
04=Turn signal times:
05=Turn on the left fog lights,Not Active,Soft ON,Hard ON
06=Turn on the right fog lights,Not Active,Soft ON,Hard ON
07=Emergency brake open double flash,OFF,ON
08=Ambient Light brightness adjustment:
09=Interior lighting holding time:
10=Interior lighting holding time:
11=Unlock internal light holding time:
12=Unlock internal light holding time:
13=Reversing rear view mirror turn angle:
14=Headlight cleaning,ON,OFF
15=Headlight cleaning interval,Once,Five times,Ten times
16=Headlight cleaning times:
17=Automatically turn off the radio and music,ON,OFF
18=Start car with brake,ON,OFF
19=Brake light flashing,OFF,flaechenvergroesserung,Brake light flashing
20=Brake lights flicker sensitivity,ECE,US,ECE_M_Sport
21=Brake lights flicker sensitivity,ECE,US
22=Folding mirrors delay time:
23=Brake lights flicker sensitivity,ECE,US,ECE_M_Sport
24=Brake lights flicker sensitivity,ECE,US
25=Personality double flash
26=High-beam assistant default ON,OFF,ON
27=Door handle LED ON when reversing,ON,OFF
28=Brake lights flicker sensitivity,ECE,US
29=Turn OFF the headunit,ON,OFF
30=Folding mirrors delay time:
31=1Fog as corners auxiliary lighting:
32=2Automatic Headlamp Leveling System(AHL),OFF,ON
33=2cornering lights,OFF,ON
34=2Left Cornering lights,OFF,ON
35=2Right Cornering lights,OFF,ON
36=2Mapping left output,ON(NSW_L),FL_L,OFF
37=0Mapping right output,ON(NSW_R),FL_R,OFF
EX04=Max value:7
EX05=when the welcome light ON
EX06=when the welcome light ON
EX09=After locking the car
EX10=After locking the car
EX17=After flameout and open the door.
EX19=When the emergency brake
EX20=negative accelerations
EX21=Speed threshold
EX22=Unit 100ms, 0 is no delay
EX23=negative accelerations
EX24=Speed threshold
EX28=Speed threshold
EX29=When flameout and open the door.
EX33=2Prerequisite:AHL ON
[FZD]
00=Locking sound confirm volume
01=Automatic Volume,ON,OFF
02=Buzzer frequency
03=Buzzer Delay
EX01=20:00-8:00 volume will be smaller
[CAS]
00=Remember last start&stop state,ON,OFF
01=Start&stop default OFF,ON,OFF
02=Turn OFF the HeadUnit,ON,OFF
EX02=After flameout and open the door.
[KOMBI]
;760  69
00=GPS time synchronization,ON,OFF
01=Dashboard instantaneous fuel consumption scale,20L/100km,30L/100km
02=Dashboard daytime background color,Orange,gray
03=Dashboard night Background Color,Orange,gray
04=Dashboard daytime luminance value:
05=Dashboard night brightness value:
06=HUD display entertainment,ON,OFF
07=HUD display phone,ON,OFF
08=HUD display phone book,ON,OFF
09=HUD display voice command,ON,OFF
10=HUD display turn signals,ON,OFF
11=Digital speed,ON,OFF
12=Trip computer reset delay (hours)
13=HUD display turn lights
14=Remind when open the door,ON,OFF
15=Fuel alarm km:
16=The second Fuel alarm km:
17=According speed curve to fix speed,ON,OFF
18=HUD display turn lights,ON,OFF
19=HUD display indicators,ON,OFF
20=Dashboard LOGO index number:
21=Display Compass,ON,OFF
22=Display digital odometer,OFF,kmh_mph,mph_kmh,mph_mph,No MPH,No KMH
EX11=BC button to call
EX12=Set to 0 - Instant Reset
EX17=OFF - Show the actual speed
EX20=MAX:15
EX21=Full LCD dashboard applicable
EX22=Latter two only later 005_000_056
[HKL]
00=A-pillar switch operating Power Trunk,OFF,ON
01=FOB to terminate and reverse Power Trunk,OFF,ON
02=FOB and A-pillar matches,OFF,ON
03=A-pillar button to open/close Power Trunk,OFF,ON
04=FOB to close Power Trunk,OFF,ON
[IHKA]
00=Air conditioning switch remember the last state,ON,OFF
01=Air conditioning switch remember the last state,OFF,ON
02=Air-conditioning cycle remember the last state,ON,OFF
03=Air-conditioning cycle remember the last state,OFF,ON
[ACSM]
;9C 9D 147
00=Seatbelt alarm delay
01=Passenger seat belt warning,ON,OFF
02=Driver's seat belt warning,ON,OFF
03=Driver seat belt status display,ON,OFF
04=Passenger seat belt status display,ON,OFF
05=Warning the driver's seat belt is opened,ON,OFF
06=Warning the Passenger seat belt is opened,ON,OFF
07=The initial seat belt warning,ON,OFF
EX00=Unit:seconds, once about 2-3
[CIC/NBT]
00=Lock/unlock Sound confirm checkbox,ON,OFF
01=1Video in motion
02=2Canceling speed lock value:
03=0Activation speed lock vlue:
04=Disclaimer display delay:
05=Reversing video Disclaimer delay:
06=Night Vision Disclaimer delay:
07=Version View menu,ON,OFF
08=Show engine power and torque,ON,OFF
09=iPhone Ringing as Bluetooth ringing,ON,OFF
10=NAVI Gas station reminders,ON,OFF
11=USB can import Geocoding,ON,OFF
12=Navigate add location menu,OFF,ON
13=NAVI Points of Interest Online Search,browser,nativ
14=1USB Play Video,OFF,1st USB,2nd USB,Both USB
15=2Xvid Video Decoder,OFF,ON
16=0VCD and SVCD video support,OFF,ON
17=Save video files to the Internal memory,OFF,ON
18=Navigation route preview,ON,OFF
19=Navigation Route preview button,OFF,ON
20=Navigation voice male/female voices,ON,OFF
21=Screen type of display,NarrowScreen,widescreen,flap,schmales_flap
22=Reversing analog image display,Vertical,Transverse
23=Daytime Running Light Checkbox,OFF,ON,Standard
24=Show Ambient Light adjustment,OFF,ON
25=Disable UPnP/WLAN Audio,ON,OFF
26=Disable UPnP/WLAN video,ON,OFF
27=Get video stream from WLAN,OFF,ON
28=Wifi switch,ON,OFF
29=WLAN connection mode,AP,Client,Both,WIFI_Direct
30=WIFI connection strength,InCar,OutDoor
31=M digital speed display,ON,OFF
32=M-HUD,ON,OFF
33=HeadUnit startup screen,Default,M,ALPINA,BMW I,bmw i,Angel,Like default,bmw,Orange grid BMW,Christmas
34=HUD show turn signals checkbox,ON,OFF
35=Oil level menu,ON,OFF
36=Release the handbrake termination Video,OFF,ON
37=Volume bar,Show,NoShow
38=Volume bar fade ended prematurely,ON,OFF
39=The volume bar display low priority,ON,OFF
40=1The controller can touch,OFF,ON
41=2Touch operation Interactive map,ON,OFF
42=2Touch for spelling,ON,OFF
43=2Touch for browser,ON,OFF
44=0High-speed lock-touch,ON,OFF
45=Compass,ON,OFF
46=Torque and xDrive status MENU,Show,NoShow
47=3D map scroll,ON,OFF
48=1Digital tire pressure monitoring system,ON,OFF
49=0Tire pressure monitoring-vehicle safety,ON,OFF
50=Head Up Display(HUD),Installed,NoInstalled
51=Show B&&O Sound menu,kein_menue,keine_insz,nur_lichtinsz,volle_insz
52=In the sound menu show Logic7_Logo,ON,OFF
53=EQ Data Definition must be loaded,stereo,hifi,tophifi,individual_sound,hk_surroundsound,highpremium,hifi_system_harmankardon
EX00=Settings - Door Locks Activate Use
EX01=Set All to 255
EX02=Set to 255 is not locked
EX03=Set to 255 is not locked
EX04=Set to 0 is not show
EX05=Set to 0 is not show
EX06=Set to 0 is not show
EX09=Only iPhone
EX14=Choose which USB to play video
EX15=support MP4
EX16=support MPEG
EX34=And in related options with KOMBI
EX38=When there are other operations
EX39=Lower priority than Warning
EX46=Show compass
EX48=!Must have the relevant hardware
EX50=Activate the installation of HUD
[CMB_MEDIA]
00=Speech Recognition,ON,OFF
01=Use Mobile phone ringtones,OFF,ON
02=Choose ringtones,RING_TONE1,RING_TONE2,RING_TONE3
EX01=Only iPhone

;***************************Application*******************************
[APP]
BT_TOOLS=&Tools
BT_FILTER=&Filtro
BT_CANCEL=&Cancella
BT_OK=&OK
BT_Close=&Chiudi
BT_Copy=&Copia in memoria
BT_HIDELIST=Codifiche
BT_SCANCAR=&1.Identifica
BT_SCANCAR_HINT=|Rileva automaticamente informazioni dopo il collegamento.
BT_LINKCAR=&2.Connetti
BT_LINKCAR_HINT=|Collegamento alla macchina.
BT_UNLINK=&Disconn
BT_UNLINK_HINT=|Disconnetti.
BT_LINKNAT=&Connetti
BT_LINKNAT_HINT=|Connessione via ICOM o NAT.
BT_READECUS=&3.leggi ECU
BT_READECUS_HINT=|Ottenere tutti i moduli della macchina.
BT_SAVEECUS=&Salva
BT_SAVEECUS_HINT=|Salva le informazioni del modulo in un file di testo.
BT_ABOUT=&Crediti
BT_ABOUT_HINT=|About this app.
BT_OPTION=&Opzioni
BT_OPTION_HINT=|Setting Options.
BT_QUIT=&Uscita
BT_QUIT_HINT=Esci dall'Applicazione
BT_READ=&4.Leggi
BT_READ_HINT=|Leggi dati dal modulo selezionato.
BT_WRITE=&5.Scrivi
BT_WRITE_HINT=|Invia codifica - write-car.
BT_BACK=&Backup
BT_BACK_HINT=|backup dei dati originali (App eseguira' il backup automaticamente).
BT_RECOVERY=&Ripristina
BT_RECOVERY=|Ripristina Codifica da backup.
BT_LOADFSC=&Leggi FSC
BT_LOADFSC_HINT=|Carica file FSC , il formato di file può essere binario o esadecimale o XML.
BT_SAVEFSC=&Salva FSC
BT_SAVEFSC_HINT=|L'FSC nella casella di modifica salvarlo come un file  binario o esadecimale.
BT_REFRESH=&Aggiorna
BT_REFRESH_HINT=|Rileggere l'elenco FSC nel Headunit.
BT_GETFSC=&Apri FSC
BT_GETFSC_HINT=|Prendi FSC selezionata da headunit.
BT_BAKFSC=&Backup Tutti FSC
BT_BAKFSC_HINT=|Backup di tutti gli FSC dell' Headunit.
BT_GEN=&Genera FSC
BT_PUTFSC=&scrivi in auto
BT_PUTFSC_HINT=|Put the activation code to headunit. when upgrade map, do not need to be input manually.
BT_GETFMAP=Ottieni da &mappa
BT_GETFMAP_HINT=|Get the country code and version number from the map file.
BT_GETFXML=Ottieni da &lookup

LB_Country=Country:
LB_VERCODE=VerCode:
LB_VIN=VIN:
LB_WARNING=ATTENZIONE:
LB_FSCNOTE=Note:Fsc Generator non e' una mia app, ringrazio l'autore originale!
LB_WAR_TIP=Scrittura fallita causa : modulo non risponde o non funziona!#Controllare rigorosamente le seguenti operazioni:#  1, La vettura deve essere ACC ON.#  2, Spegnere l'aria condizionata e altri moduli ad alta potenza.#  3, Avviare la macchina, ma deve essere spenta quando si scrive in modulo CAS / BODY.#  4, Non utilizzare la macchina durante la scrittura.#  5, Assicurarsi che la connessione non sara' interrotto.#  6, Se dovesse fallire, si prega di fare clic sul pulsante di ripristino per riparare.
LB_BAKNOTE=    Se è la prima lettura, per ragioni di sicurezza, App effettua un backup di sicurezza.#I file di backup vengono memorizzati nella cartella dell'app, la sottodirectory è denominata con VIN.#Assicurarsi di mantenere questa directory e file,##    Clicca "Ripristina" per ripristinare i dati di backup, Se si ha bisogno.
LB_IP=Scan IP:
LB_LINKPORT=Link Port:
LB_SCANPORT=Scan Port:
LB_BAKTIT=Seleziona File per ripristino:
LB_HIDELISTTIP=varie opzioni dell' auto.
LB_SCANING=Rilevo la Vettura, attendere prego ....
LB_SCANTIP=1.La vettura deve essere ACC ON.#2.Indirizzo IP impostato su automatico DHCP.#3.Il Firewall non blocca l'accesso alla rete.
LB_ENTER=Invio#Per Confermare
LB_IMPORTANT=IMPORTANTE:
LB_CDATE=Data creazione:
LB_ICOM=    Ottieni IP e porta dell' ICOM (di solito: 169.254.92.38:50160),e inseriscilo qui sotto.
MI_ECU_DATE=Leggi Manufacturing Data ECU 
MI_ECU_PROG=Leggi Programming Counter
MI_ECU_VOLT=Rileva voltaggio
MI_CAR_STEP=Livello Integrazione
MI_ECU_CPS=Leggi CPS
MI_ECU_SVK1=Leggi Current SVK
MI_ECU_SVK2=Leggi System Supplier SVK
MI_ECU_SVK3=Leggi Plant SVK
MI_SVK_BAK1=Leggi Backup SVK 1
MI_SVK_BAK2=Leggi Backup SVK 2
MI_SVK_BAK3=Leggi Backup SVK 3
MI_ECU_DTC=Cancella DTC selezionati in ECU
MI_ALL_DTC=Cancella tutti DTC
MI_ECU_RE=Restart ECU
MI_GEARBOX=Ripristino dati di trasmissione (abitudini di guida in memoria)
MI_GETGEARBOX=Vedi valori di adattamento cambio
MI_DATETIME=Sincronizza la data e l'ora per il Kombi

CH_NONEXT=Non mostrare più
CH_AutoDetect=Scansione automatica dopo l'avvio.
CH_AutoLink=Connetti automaticamente all'auto.
CH_AutoRead=Leggi automaticamente la lista ECU.
CH_AUTOSETTIME=sincronizza KOMBI dopo la codifica 

GB_CAROPTION=Auto
GB_SYSOPTION=Sistema
GB_ECUS=ECUs
GB_CODE=Coding

PA_WAIT=In comunicazione, attendere ...

LV_BAK=Backup Files,Backup Date
LV_FSC=Number,Index,Status

ListView_HINT=Blue has hidden features,if it is red color,please contact me to upgrade.
HideView_HINT=Set it as required and written to the car go into effect.

ST_TIMEOUT=Timeout!
ST_GETPRESSURES=Get Clutch fill pressures...
ST_GETFILLTIME=Get Rapid fill times...
ST_ADAP=Clutch fill pressures:#   Clutch A: %D.0 mbar#   Clutch B: %D.0 mbar#   Clutch C: %D.0 mbar#   Clutch D: %D.0 mbar#   Clutch E: %D.0 mbar##Rapid fill times:#   Clutch A: %D.0 ms#   Clutch B: %D.0 ms#   Clutch C: %D.0 ms#   Clutch D: %D.0 ms#   Clutch E: %D.0 ms  
ST_GENFAIL=Calcolo fallito!
ST_SELTYPE=Si prega di selezionare il tipo di unita' principale prima.
ST_MAPINFO=Country Code:%S Ver Code:%S
ST_FSCEXE=Non posso aprireil generatore, il generatore non esiste.
ST_FORMATERR=Formato file errato!
ST_BAKFSC=Backup %S:
ST_BAKEND=Fine Backup...
ST_NOBAKFSC=FSC Backup Fallito!#Clicca il pulsante aggiorna e riprova.
ST_FSCVIN=Get FSC VIN...
ST_WRCODE=Scrivi codice di attivazione...
ST_LOWCODE=Il codice di attivazione mappa e' inferiore alla versione
ST_WRCODEERR=Scrittura codice di attivazione non riuscita, pls riprovare...
ST_CPSERR=VIN errore di formato, non si può continuare.
ST_STEP_CUR=Current:%S-%d-%d-%d
ST_STEP_LAS=Last:%S-%d-%d-%d
ST_STEP_SHI=Shipment:%S-%d-%d-%d
ST_SET_EXT_DS=Set esteso di sessione diagnostica...
ST_READ_FTP=Leggi Parametri Flash Timing...
ST_READ_ADS=Leggi sessione diagnostica attiva...
ST_SDS=Imposta sessione predefinita...
ST_SRESET=Invio comando restart...
ST_WAITRE=Attesa per il riavvio del modulo...
ST_TESTM=Missione Finale di testing...
ST_MISSOK=Missione completa...
ST_MISSTER=Missione Terminata...
ST_NOP=Chiaro stato di esecuzione...
ST_REDY=Preparare attivita' di codifica del veicolo ...
ST_SVK=Ottieni SVK...
ST_SAR=Richiesta sicurezza di accesso...
ST_ACCVER=verifica di accesso...
ST_ACCVERERR=Verifica di accesso non riuscita!(%S)
ST_SVF_MT=Verifica della firma fallita(%S), Missione terminata...
ST_TRYLATER=non in grado di garantire l'accesso, si prega di riprovare più tardi ...
ST_FTRSA=Richiesta accesso sicuro fallita...
ST_WRITING=Scrittura...
ST_WCPS=Scrittura CPS...
ST_VWD=Verifica dati scritti...
ST_CHECKSI=Verificare la firma...
ST_GET_CAFD=Get [%S] InformazioniCAFD...
ST_CHECK_V=[%S] Tensione Rilevata:%S V.
ST_CHECKV=Rilevamento tensione...
ST_CHECKVERR=Impossibile rilevare informazioni sulla tensione,#Assicurarsi che la tensione dell' auto sia sufficiente e stabile!#Continuare a scrivere?
ST_V_LOW=Il rilevamento della tensione, è quasi critico,#Al fine di garantire sicurezza durante la scrittura,#Si prega di scrivere dopo la ricarica.
ST_CAS=Il codice corrente, per avviamento un'unita' di controllo sistema (%S).Si prega di spegnere il motore per continuare ...
ST_PROGCOUNT=ECU(%S)Contatore programmazione:%D Max Value:%D...
ST_NOINFO=Queste informazioni non vengono registrate..
ST_MODEDATE=ECU(%S)Manufacturing Date:%S-%S-%S
ST_CLEAR_DTC=ECU:%S DTC Cancellati...
ST_SVFAIL=Verifica della firma non riuscita, missione fallita.
ST_KEYFAIL=Verifica Key fallita, Annullo...
ST_WRITEFAIL=Scrittura Fallita!#fare clic sul pulsante Ripristina per ripristinare...
ST_NOTRECVCOD=La centralina non può ricevere codifica,#Riprova piu' tardi ...
ST_TIMEINVA=Time-domain stato non valido,#Riprova piu' tardi...
ST_WRITETIMEOUT=Risposta Timeout , riprova...
ST_VIN_FAIL=Controllo fallito [%S] ...
ST_DESKTOP=Software sul desktop.#Poiché il software genera le directory e i file necessari,#E esegue automaticamente il backup dei dati originali della vettura,#Si consiglia la copia del software in una directory dedicata.#Rieseguire il programma ora?
ST_SCAN_CAR=Rileva auto...
ST_SCANED=connettersi dopo il rilevamento auto...
ST_RELINK=Per ricollegare, prima disconnettere la connessione corrente.
ST_LINKING=Connesso...
ST_LINKSER=Collegamento al servizio...
ST_GETVIN=Ottieni VIN...
ST_HAND=in attesa di connessione...
ST_UNLINK=Disconnesso...
ST_COM_WAIT=Comando precedente non è terminato, si prega di attendere ...
ST_GETECU=Leggi ECU dell' auto...
ST_UPDATE=Parte dei dati hanno bisogno di aggiornamento, si prega di contattarmi...
ST_SELECU=Scegliere una ECU da leggere ...
ST_NOSUP=Non supporta questo modulo...
ST_CODINST=Codificando il Kombi, la manutenzione, l'ora e altre informazioni andranno perse!#codifico?
ST_NODATA=La versione attuale non comprende questa ECU ...
ST_UPDATE=Dati incompleti, Aggiorna...
ST_READCODE=Sto leggendo...
ST_NEEDUP=Dati incorretti, pls aggiorna dati ...
ST_DATERR=Dati non corretti, impossibile completare ...
ST_CHECK=Controllo dell'integrita' dei dati...
ST_CHECKERR=La convalida dei dati non riuscita, scrittura fattita...
ST_WRIT=Le modifiche avranno effetto dopo la scrittura.
ST_READFIRST=Prima leggi...
ST_AUTOBAK=Backup Automatico dei dati...
ST_BACKUP=Backup dei dati...
ST_OVERBAK=Backup esiste gia', vuoi sovrascrivere il backup?
ST_BAKERR=Errore critico:#Incapace di eseguire backup, l'operazione di backup è molto importante!#Controllare ed eliminare la causa di questo errore!
ST_INPUTERR=Valore inserito non corretto! modifica fallita...
ST_OUTRANGE=Valore fuori range,..interrotto...
ST_NOKEY=Leggi dati errore!(%S)
ST_BAKCON=Confermare il ritorno allo stato di backup dell'ECU?
ST_CLEARDTC=Confermi la cancellazione dei DTC dell'ECU ?
ST_ALLDTC=Confermi la cancellazione di tutti i DTC?
ST_CONRESTART=Confermi il riavvio dell'ECU selezionata?
ST_SELAECU=Scegliere una ECU da ripristinare...
ST_BACKMODIED=Il file di backup è stato modificato, non può essere ripristinato ...
ST_NOSAVE=Niente da salvare....
ST_NOCOMP=Non completato, quindi rimanete sintonizzati ....^_^
ST_CODIHKA=Alcuni modelli di auto non possono spegnere l'aria condizionata dopo la codifica.#Questo è un fenomeno normale,#essa può essere ripristinata dopo l'esecuzione alcune volte.