;********Special symbols:  (Please keep the format integrity.)********
;  #-as a newline, In the middle of the string,
;  !-Displayed in red at the CodingList,First char of the string
;  ,-Separator
;  &-Shortcuts delimiter
;  %S,%D-Replace strings and numbers
;  |-Status Bar hint
;*********************************************************************

;****************************Language*********************************
Lang=French
;*********************************************************************

;*****************Translator copyright information********************
;Be displayed in the application
Copyright=Bienvenue ...#Cette APP est gratuite , vous ne devez pas payer de frais. #Mon email: snzdl555@gmail.com#Translate by scorpium59
;*********************************************************************

;***************************Application*******************************
[APP]
BT_TOOLS=&Outils
BT_FILTER=&Filtre
BT_CANCEL=&Annuler
BT_OK=&OK
BT_Close=&Fermer
BT_SAVE=&Sauver
BT_ADD=&Ajouter
BT_INSERT=&Inserer
BT_Copy=&Copier dans presse papier
BT_HIDELIST=Liste codage
BT_SCANCAR=&1.Detect Vehicule
BT_SCANCAR_HINT=|Detecter automatiquement les informations de vehicule pour la connexion..
BT_LINKCAR=&2.Connectez
BT_LINKCAR_HINT=|Connexion au véhicule.
BT_UNLINK=&Deconn
BT_UNLINK_HINT=|Deconnecter.
BT_LINKNAT=&Connect
BT_LINKNAT_HINT=|Connexion avec ICOM ou NAT.
BT_READECUS=&3.Obtenir liste ECU
BT_READECUS_HINT=|Obtenir toutes les informations des modules du véhicule.
BT_SAVEECUS=&Sauver
BT_SAVEECUS_HINT=|Sauver les informations de module dans un fichier texte.
BT_ABOUT=&A propos
BT_ABOUT_HINT=|A propos de l'application.
BT_OPTION=&Option
BT_OPTION_HINT=|Reglage option.
BT_QUIT=&Quitter
BT_QUIT_HINT=Quitter application.
BT_READ=&4.Lire
BT_READ_HINT=|Lire les donnees du module selectionne.
BT_WRITE=&5.Ecrire
BT_WRITE_HINT=|Ecrire le codage sur vehicule.
BT_BACK=&Sauvegarde
BT_BACK_HINT=|Sauvegarde de donnees originale(App sera automatiquement sauvegarde).
BT_RECOVERY=&Restaurer
BT_RECOVERY=|Retour codage etat de sauvegarde.
BT_LOADFSC=&Charge FSC
BT_LOADFSC_HINT=|Charge fichier FSC, Le format de fichier peut etre binaire, hexadecimal ou XML.
BT_SAVEFSC=&Enregistrer sous
BT_SAVEFSC_HINT=|Le FSC dans la zone d'edition enregistre comme un format de fichier binaire ou hexadecimal.
BT_REFRESH=&Rafraichir
BT_REFRESH_HINT=|Relire liste FSC dans l'unite de tete.
BT_GETFSC=&Obtenez FSC
BT_GETFSC_HINT=|Obtenez le FSC de l'unité de tete.
BT_BAKFSC=&Sauvegarder tous les FSC
BT_BAKFSC_HINT=|Sauvegarder tous les FSC dans l'unite de tete.
BT_GEN=&Generer
BT_PUTFSC=&Ecriture dans le vehicule
BT_PUTFSC_HINT=|Mettez le code d'activation dans l'unite de tete. Lorsque la carte est mise a jour, le FSC ne doit pas etre entre manuellement.
BT_GETFMAP=Obtenir de &carte
BT_GETFMAP_HINT=|Obtenir le code du pays et le numero de version du fichier de carte.
BT_GETFXML=Obtenir de &lookup.xml
BT_FILTER_HINT=| Afficher uniquement le fichier de configuration (KeyList.ini) mots-cles.
BT_SEARCH_HINT=| Rechercher mots-cles specifie.
BT_CUSTOM=&Modifier
BT_DOWNLOAD=&Telecharger
BT_DOWNNOW=&Telecharger maintenant
BT_CLEARANDRE=Effacer tout et &relire

LB_Country=Pays:
LB_VERCODE=VerCode:
LB_VIN=VIN:
LB_WARNING=ATTENTION:
LB_FSCNOTE=Note:le generateur n'est pas mon app, remerciez l'auteur original!
LB_WAR_TIP=L'echec de l'ecriture entrainera l'invalidite du module ou pas Travail!#Veuillez strictement procedez comme suit:#  1, Le vehicule doit avoir le contact.#  2, Eteignez la climatisation et autre module de haute puissance.#  3, Demarrez le vehicule, mais il doit etre mis hors tension lors du codage CAS / Module carrosserie.#  4, Ne pas toucher au vehicule lors de l'ecriture.#  5, Assurez-vous que la connexion ne sera pas
interrompu.#  6, Si elle echoue, s'il vous plait cliquer sur le bouton de restauration pour fixer..
LB_BAKNOTE=    Si la premiere lecture, pour des raisons de securite, App
sauvegarde automatiquement.#Les fichiers de sauvegarde sont stockes dans le repertoire de l'application,le sous repertoire nomme avec le VIN.#Veillez a conserver ce repertoire et fichiers,##    Cliquez sur le bouton "Restaurer" pour restaurer ces donnees de sauvegarde, si vous avez besoin.
LB_IP=Scan IP:
LB_LINKPORT=Lien Port:
LB_SCANPORT=Scan Port:
LB_BAKTIT=Selectionner un fichier a restaurer:
LB_HIDELISTTIP=Options variable par vehicule.
LB_SCANING=Detection du vehicule, attendez svp ....
LB_SCANTIP=1.Le vehicule doit avoir le contact.#2.Adresse IP se regle automatiquementObtenir.#3.Le firewall ne doit pas interdire l'acces au reseau.
LB_ENTRER=Entrer cle#Pour confirmer#Apres l'entree
LB_IMPORTANT=IMPORTANT:
LB_CDATE=Date de creation:
LB_ICOM=    Obtenir IP et port de l'ICOM (comme: 169.254.92.38:50160),et entrer dans la zone d'edition.
LB_WFAIL=Operation d'ecriture anormale, echec de la mission, Il est recommande d'essayer de nouveau ou de restaurer une sauvegarde, si la tache est termine, le module courant peut ne pas fonctionner correctement (Si plusieurs tentative ne fonctionnent pas, il est recommande d'utiliser le fix ESYS.)
LB_KEYNAME=Mot cle:
LB_DES=Description:
LB_EXDES=Descr prolonge:
LB_TYPE=Type:
LB_ITEM=Liste de choix:
LB_LANG=Choisir la langue:
LB_TIMING=Ecrire synchro de reglage fin(Unit:ms):
LB_TIMETIP=Si erreurs a repetition, augmenter a la valeur approprie.
LB_DOWNTIP=Module courant (ECU) pas d'element personnalise, cliquezsur le bouton "Personnalise" et telecharger les donnees personnalisees, essayer de nouveau. Vous pouvez egalement definir vos propres mots-cles par l'editeur personnalise de mot cle, codage plus facile et rapide.
LB_DOWNDTC=Fault code documentation is empty, Click on the download button below, You can view the corresponding description text.


RG_PROC_CAP=Choisissez un mode de traitement
RG_PROC_ITEMS="essayer a nouveau","Restaurer une sauvegarde","Tache de terminaison (module peut ne pas fonctionner!)"
RG_DOWNTYPE_CAP=Mode de telechargement:
RG_DOWNTYPE_ITEMS="Ajouter mise a jour","Ecraser existante"
RG_LANG_CAP=Choisir le language:

MI_ECU_DATE=Lire ECU Date fabrication
MI_ECU_PROG=Lire programmation compteur
MI_ECU_VOLT=Detection de tension
MI_CAR_STEP=Niveau integration
MI_FSCTOOLS=FSC Tools
MI_ECU_CPS=Lire CPS
MI_ECU_SVK1=Lire actuel SVK
MI_ECU_SVK2=Lire fournisseur systeme SVK
MI_ECU_SVK3=Lire Plante SVK
MI_SVK_BAK1=Lire sauvegarde SVK 1
MI_SVK_BAK2=Lire sauvegarde SVK 2
MI_SVK_BAK3=Lire sauvegarde SVK 3
MI_ECU_DTC=Effacer selection ECU's DTC
MI_ALL_DTC=Effacer tout DTC
MI_ECU_RE=Redemarrer ECU
MI_GEARBOX=Reinitialiser les valeurs d'adaptation Transmission(Habitudes de conduite memoire)
MI_GETGEARBOX=Afficher valeur d'adaptation transmission
MI_DATETIME=Synchroniser la date et l'heure du KOMBI
MI_PHONENUM=Numero predefini unite de tete
MI_BTNAME=Nom de l'appareil bluetooth
MI_READDTC=Lire DTC

CH_NONEXT=Ne pas montrer de nouveau
CH_AutoDetect=Scan automatique du vehicule apres demarrage.
CH_AutoLink=Connection automatique du vehicule.
CH_AutoRead=Obtenir list ECU automatiquement.
CH_AUTOSETTIME=Synchro auto de l'heure apres codage KOMBI
CH_RESETFIRST=Redemmarrer le module puis executer

GB_CAROPTION=Vehicule
GB_SYSOPTION=Systeme
GB_ECUS=ECUs
GB_CODE=Codage
GB_EDITKEY=Editer mot cle
GB_KEYLIST=Modifier liste mot cle

CB_TYPE=Defaut,"Zone d'edition numerique","Liste personnalise"

PA_WAIT=Communication, patientez svp ...

LV_BAK=Fichiers de sauveagrde,Date de sauvegarde
LV_FSC=Nombre,Index,Statut
LV_KEYS=Description,mot cles,Articles

TS_Custom=Personnalise
TS_Normal=Normal

TB_CUSTOM=Enregistrer,Ajouter,Supprimer,Editer,"Deplacer a gauche","Deplacer a droite","Deplacer en haut","Deplacer en bas",Bloc-notes,Telecharger

ListView_HINT=Bleu a des fonctions caches,si elle est de couleur rouge, svp me contacter pour mettre a niveau.
HideView_HINT=Regler le au besoin et l'ecriture au vehicule entrera en vigueur.

ST_TIMEOUT=Timeout!
ST_GETPRESSURES=Obtenez des pressions de remplissage d'embrayage...
ST_GETFILLTIME=Obtenez temps de remplissage rapide...
ST_ADAP=Embrayage pressions de remplissage:#   Embrayage A: %D.0 mbar#   Embrayage B: %D.0 mbar#   Embrayage C: %D.0 mbar#   Embrayage D: %D.0 mbar#   Embrayage E: %D.0 mbar##temps de remplissage rapide:#   Embrayage A: %D.0 ms#   Embrayage B: %D.0 ms#   Embrayage C: %D.0 ms#   Embrayage D: %D.0 ms#   Embrayage E: %D.0 ms  
ST_GENFAIL=Echec calcul!
ST_SELTYPE=Svp selectionner tete d'unite en premier.
ST_MAPINFO=Pays Code:%S Ver Code:%S
ST_FSCEXE=Appel generateur impossible, le generateur n'existe pas.
ST_FORMATERR=Erreur format de fichier!
ST_BAKFSC=Sauvegarde %S:
ST_BAKEND=Fin de sauvegarde...
ST_NOBAKFSC=FSC Echec sauvegarde!#Cliquez actualiser et re-essayer.
ST_FSCVIN=Obtenez FSC VIN...
ST_WRCODE=Ecrire code activation...
ST_LOWCODE=Le code d'activation est inferieur a la version de carte
ST_WRCODEERR=Echec de l'ecriture du code,svp re-essayer...
ST_CPSERR=VIN erreur format, ne peut continuer.
ST_STEP_CUR=Actuel:%S-%d-%d-%d
ST_STEP_LAS=Dernier:%S-%d-%d-%d
ST_STEP_SHI=Expedition:%S-%d-%d-%d
ST_SET_EXT_DS=Definir session diagnostic etendu...
ST_READ_FTP=Lire parametre de synchro du flash...
ST_READ_ADS=Lire la session active diagnostic...
ST_SDS=Definir session par defaut...
ST_SRESET=Envoi commande redemarrer...
ST_WAITRE=Attente redemarrage modules...
ST_TESTM=Test mission finale...
ST_MISSOK=Mission accomplie...
ST_MISSTER=Mission Terminee...
ST_NOP=Effacer etat d'execution...
ST_REDY=Preparer le codage du vehicule...
ST_SVK=Obtenir SVK...
ST_SAR=Demande d'acces securite...
ST_ACCVER=Verification acces...
ST_ACCVERERR=Echec verification d'acces!(%S)
ST_SVF_MT=Echec verification signature(%S), Mission terminee...
ST_TRYLATER=Impossible de securiser l'acces, svp re-essayer plus tard ...
ST_FTRSA=Echec demande d'acces securise...
ST_WRITING=Ecriture...
ST_WCPS=Ecriture CPS...
ST_VWD=Verifier les infos ecrites...
ST_CHECKSI=Verifier la signature...
ST_GET_CAFD=Obtenir [%S] CAFD information...
ST_CHECK_V=[%S]Tension detectee:%S V.
ST_CHECKV=Detection tension vehicule...
ST_CHECKVERR=Impossible de detecter les informations de tension,#Verifier que la tension vehicule est suffisante et stable!#Continuer pour ecrire?
ST_V_LOW=Tension critique,#afin de garantir la securite,#svp ecrire apres charge batterie.
ST_CAS=Le code actuel pour le demarrage de l'unite de controle systeme (%S).Svp eteindre le moteur continu ...
ST_PROGCOUNT=ECU(%S)Programmation compteur:%D Valeur max:%D...
ST_NOINFO=Ces informations ne sont pas enregistrees..
ST_MODEDATE=ECU(%S)Date de fabrication:%S-%S-%S
ST_CLEAR_DTC=ECU:%S DTC efface...
ST_SVFAIL=Echec verification signature, mission echoue.
ST_KEYFAIL=Echec verification cle, annule...
ST_WRITEFAIL=Echec ecriture!#Cliquer sur restaurer...
ST_NOTRECVCOD=L'ECU ne peut recevoir le codage,#Svp essayer plus tard ...
ST_TIMEINVA=Etat domaine temporel invalide,#Svp essayer plus tard...
ST_WRITETIMEOUT=Delai de reponse, Svp essayer ...
ST_VIN_FAIL=Echec verification [%S] ...
ST_DESKTOP=Logiciel situe sur le bureau.#Car le logiciel va generer les repertoires et fichiers necessaire,#Et sauvegarder automatiquement les donnees d'origine du vehicule,#Recommande de copier le logiciel dans un repertoire dedie.#Executer tout de meme le logiciel?
ST_SCAN_CAR=Detection vehicule...
ST_SCANED=Svp se connecter apres detection vehicule ...
ST_RELINK=Pour reconnecter, Deconnecter la connexion en cours en premier.
ST_LINKING=Connection ...
ST_LINKSER=Connection service ...
ST_GETVIN=Obtenir VIN...
ST_HAND=Liaison...
ST_UNLINK=Deconnecter...
ST_COM_WAIT=Precedente commande non terminee, patienter svp ...
ST_GETECU=Obtenir ECUs vehicule...
ST_UPDATE=Une partie des donnees doit etre mise a jour, svp contactez moi...
ST_SELECU=Svp choisir un ECU pour lire ...
ST_NOSUP=Module non supporte...
ST_CODINST=Code donnees tableau de bord, maintenance, tHeure et autre infos seront perdus!#Toujours coder?
ST_NODATA=La version actuelle n'a pas les donnees de l'ECU ...
ST_UPDATE=Donnees incomplete, mettre a jour svp...
ST_READCODE=Lecture...
ST_NEEDUP=Donnees incorrect, mettre a jour donnees svp ...
ST_DATERR=Donnees incorrect, impossible de terminer ...
ST_CHECK=Verification integrite donnees...
ST_CHECKERR=Echec validation donnees, pas d'ecriture a...
ST_WRIT=Modification prennet effet apres ecriture.
ST_READFIRST=Svp lire en premier...
ST_AUTOBAK=Sauvegarde automatique donnees...
ST_BACKUP=Sauvegarde donees...
ST_OVERBAK=Sauvegarde existe deja, souhaitez vous remplacer la sauvegarde?
ST_BAKERR=Erreur critique:#Impossible de sauvegarder, l'operation de sauvegarde est tres importante!#Verifier et eliminer la cause de l'erreur!
ST_INPUTERR=Valeur incorrect entree! Echec modification...
ST_OUTRANGE=Valeur hors plage, interception...
ST_NOKEY=Obtenez erreur de donnees cle!(%S)
ST_BAKCON=Confirmer le retour de l'ECU selectionne pour le statut de sauvegarde?
ST_CLEARDTC=Confimer effacement ECU selectionne DTC?
ST_ALLDTC=Confirm Effacer tout DTC?
ST_CONRESTART=Confirmer redemarrage ECU selectionne?
ST_SELAECU=Svp choisir un ECU pour restaurer...
ST_BACKMODIED=Le fichier de sauvegarde a ete modifie, ne peut etre restaure ...
ST_NOSAVE=Rien a sauver....
ST_NOCOMP=Non termine, donc rester attentif ....^_^
ST_CODIHKA=Certains vehicule ne peuvent eteindre l'air conditionne apres codage.#C'est un phenomene normal, #il peut etre restaure apres avoir fonctionne quelque temps.
ST_DOWNFAIL=Impossible de telecharger, causes possible:#1. Reseau injoignable.#2. Les informations ne sont pas dipsonible dans la langue selectionnee.
ST_UPCOUNT=Mise a jour mots cles: %D
ST_POSSAVE=Mots cles changent emplacement, besoin de re-sauver.#Que ce soit ou non pour sauver?
ST_DELKEY=Confirmer pour supprimer le mot cle selectionne?
ST_KEYEMPT=Actuels mots cles personnalises vide, maintenant se connecter au reseau et mettre a jour?
ST_ECUCHANG=Liste ECU a change, svp re-lire le codage...