;********Special symbols:  (Please keep the format integrity.)********
;  #-as a newline, In the middle of the string,
;  !-Displayed in red at the CodingList,First char of the string
;  ,-Separator
;  &-Shortcuts delimiter
;  %S,%D-Replace strings and numbers
;  |-Status Bar hint
;*********************************************************************

;****************************Language*********************************
Lang=German
;*********************************************************************

;*****************Translator copyright information********************
;Be displayed in the application
Copyright=Welcome ...#This app is free, you do not need to pay any fees. #My email: snzdl555@gmail.com#Translate by MoeJoe
;*********************************************************************

;***************************Application*******************************
[APP]
BT_TOOLS=&Tools
BT_FILTER=&Filter
BT_CANCEL=&Abbrechen
BT_OK=&OK
BT_Close=&Schliessen
BT_SAVE=&Speichern
BT_ADD=&Hinzufügen
BT_INSERT=&Einfügen
BT_Copy=&In Zwischenablage kopieren
BT_HIDELIST=Codier Liste
BT_SCANCAR=&1.Auto erkennen
BT_SCANCAR_HINT=|Automatisch Fahrzeuginformation erkennen zum Verbinden.
BT_LINKCAR=&2.Verbinden
BT_LINKCAR_HINT=|Verbinden zum Auto.
BT_UNLINK=&Trennen
BT_UNLINK_HINT=|Trennen.
BT_LINKNAT=&Verbinden
BT_LINKNAT_HINT=|Verbinden mit ICOM oder NAT.
BT_LeseECUS=&3.Lade ECU Liste
BT_LeseECUS_HINT=|Lade alle Modulinformationen vom Auto.
BT_SAVEECUS=&Speichern
BT_SAVEECUS_HINT=|Speicern der Modulinformationen in eine Text Datei.
BT_ABOUT=&Ueber
BT_ABOUT_HINT=|Über dieses App.
BT_OPTION=&Optionen
BT_OPTION_HINT=|Einstellungen.
BT_QUIT=&Beenden
BT_QUIT_HINT=Programm beenden.
BT_Lese=&4.Lesen
BT_Lese_HINT=|Daten vom selektierten Modul lesen.
BT_WRITE=&5.Schreiben
BT_WRITE_HINT=|Put coding write-car.
BT_BACK=&Backup
BT_BACK_HINT=|Erstellen eines automatisches Backups der Daten.
BT_RECOVERY=&Zuruecksetzen
BT_RECOVERY=|Zurueckcodieren zum Backup Status.
BT_LOADFSC=&Lade FSC
BT_LOADFSC_HINT=|Lade FSC Datei (Dateiformat: Binaer, Hexadezimal oder XML).
BT_SAVEFSC=&Speichern als
BT_SAVEFSC_HINT=|Den FSC in der Editierbox speichern als Binaer oder Hexadezimal Datei.
BT_REFRESH=&Neuladen
BT_REFRESH_HINT=|Neulesen der FSC Liste der HeadUnit.
BT_GETFSC=&Lade FSC
BT_GETFSC_HINT=|Lade die selektierte FSC von der HeadUnit.
BT_BAKFSC=&Backup aller FSC
BT_BAKFSC_HINT=|Backup aller FSC in der HeadUnit.
BT_GEN=&Generieren
BT_PUTFSC=&Programmieren ins Fahrzeug
BT_PUTFSC_HINT=|Schreibe Aktivierungscode in die HeadUnit. Beim Kartenupdate, ist keine manuelle Eingabe notwendig.
BT_GETFMAP=Lade von &map
BT_GETFMAP_HINT=|Lade den Ländercode und Version vom der Map Datei.
BT_GETFXML=Lade von &lookup.xml
BT_FILTER_HINT=| Zeige Konfigurationsdatei (KeyList.ini).
BT_SEARCH_HINT=| Such beliebiges Stichwor.
BT_CUSTOM=&Anpassen
BT_DOWNLOAD=&Download
BT_DOWNNOW=&Download Now
BT_CLEARANDRE=Clear all and &re-read

LB_Country=Land:
LB_VERCODE=VerCode:
LB_VIN=VIN:
LB_WARNING=WARNUNG:
LB_FSCNOTE=Notiz:Generator ist nicht mein App, Dank dem Original Author!
LB_WAR_TIP=Write failed will cause the module to disability or does not work!#Please strictly do the following:#  1, The car must be ACC ON.#  2, Turn off air conditioning and other high-power module.#  3, Start the car, but must be turned off when coding CAS / BODY module.#  4, Do not operating car when writing.#  5, Ensure that the connection will not be interrupted.#  6, Should it fail, please click the restore button to fix.
LB_BAKNOTE=    If the first Lese, for safety reasons, App will automatically backup it.#Backup files are stored in the app directory,the subdirectory named with VIN.#Be sure to retain this directory and files,##    Click the "Restore" button to restore this backup data, If you need.
LB_IP=Scan IP:
LB_LINKPORT=Link Port:
LB_SCANPORT=Scan Port:
LB_BAKTIT=Datei fuer Restore:
LB_HIDELISTTIP=Optionen variieren vom Fahrzeug.
LB_SCANING=Erkenne FZG, bitte warten ....
LB_SCANTIP=1.Zuendung muss an sein.#2.IP addresse auf automatisch.#3.Firewall deaktivieren.
LB_ENTER=Enter Key#To Confirm#After Input
LB_IMPORTANT=WICHTIG:
LB_CDATE=Erstelldatum:
LB_ICOM=    Get ICOM's IP and port (like: 169.254.92.38:50160),And input in the edit box.
LB_WFAIL=Abnormal write operation, the mission fails, Recommended to try again or restore a backup, if the task is terminated, the current module may not work properly. (If multiple attempts are still unable to successfully recommended use ESys fix.)
LB_KEYNAME=Keyword:
LB_DES=Beschreibung:
LB_EXDES=Erweiterte Des:
LB_TYPE=Typ:
LB_ITEM=List items:
LB_LANG=Sprache auswaehlen:
LB_TIMING=Write timing fine-tuning(Unit:ms):
LB_TIMETIP=If repeatedly write error, please appropriate to increase this value.
LB_DOWNTIP=Current module (ECU) no custom item, click the "Custom" button and download the custom data and try again. You can also define your own keywords by custom keywords editor, coding easier and faster.
LB_DOWNDTC=Fault code documentation is empty, Click on the download button below, You can view the corresponding description text.

RG_PROC_CAP=Waehle einen Modus
RG_PROC_ITEMS="Neuu versuchen","Ein Backup zurueckspielen","Abbrechen (Modul kann beschaedigt werden!)"
RG_DOWNTYPE_CAP=Download Modus:
RG_DOWNTYPE_ITEMS="Updates hinzufuegen","Exyistierende ueberschreiben"
RG_LANG_CAP=Choose a language:

MI_ECU_DATE=Lese ECU Hersteller Daten
MI_ECU_PROG=Lese Programmier Counter
MI_ECU_VOLT=Erkenne Spannung
MI_CAR_STEP=Integration step
MI_ECU_CPS=Lese CPS
MI_FSCTOOLS=FSC Tools
MI_ECU_SVK1=Lese markierte SVK
MI_ECU_SVK2=Lese System Hersteller SVK
MI_ECU_SVK3=Lese Plant SVK
MI_SVK_BAK1=Lese Backup SVK 1
MI_SVK_BAK2=Lese Backup SVK 2
MI_SVK_BAK3=Lese Backup SVK 3
MI_ECU_DTC=Loesche markierte ECU's DTC
MI_ALL_DTC=Loesche alle DTC
MI_ECU_RE=Restart ECU
MI_GEARBOX=Reset Transmission adaptation values(Driving Habits Memory)
MI_GETGEARBOX=Display Transmission adaptation values
MI_DATETIME=Synchronisiere Datum und Zeit zum KOMBI
MI_PHONENUM=Headunit preset phone numbers
MI_BTNAME=Bluetooth device name
MI_READDTC=Read DTC

CH_NONEXT=Nicht erneut zeigen
CH_AutoDetect=Automatic scan FZG nach Startup.
CH_AutoLink=Automatisch FZG verbinden
CH_AutoLese=Automatisch lade ECU Liste.
CH_AUTOSETTIME=Auto Zeit Synchronisation nach KOMBI codierung
CH_RESETFIRST=Restart the module and then execute

GB_CAROPTION=FZG
GB_SYSOPTION=System
GB_ECUS=ECUs
GB_CODE=Codiere
GB_EDITKEY=Bearbeite Suchwort
GB_KEYLIST=Custom keyword list

CB_TYPE=Default,"Digital editing box","Custom list"

PA_WAIT=Communicating, please wait ...

LV_BAK=Backup Files,Backup Date
LV_FSC=Number,Index,Status
LV_KEYS=Description,Keyword,Items

TS_Custom=Custom
TS_Normal=Normal

TB_CUSTOM=Save,Add,Remove,Edit,"Move left","Move Right","Move up","Move Down",Notepad,Download

ListView_HINT=Blue has hidden features,if it is red color,please contact me to upgrade.
HideView_HINT=Set it as required and written to the car go into effect.

ST_TIMEOUT=Timeout!
ST_GETPRESSURES=Get Clutch fill pressures...
ST_GETFILLTIME=Get Rapid fill times...
ST_ADAP=Clutch fill pressures:#   Clutch A: %D.0 mbar#   Clutch B: %D.0 mbar#   Clutch C: %D.0 mbar#   Clutch D: %D.0 mbar#   Clutch E: %D.0 mbar##Rapid fill times:#   Clutch A: %D.0 ms#   Clutch B: %D.0 ms#   Clutch C: %D.0 ms#   Clutch D: %D.0 ms#   Clutch E: %D.0 ms  
ST_GENFAIL=Calculate failed!
ST_SELTYPE=Please select the headunit type first.
ST_MAPINFO=Country Code:%S Ver Code:%S
ST_FSCEXE=Cannot call generator, the generator does not exist.
ST_FORMATERR=File format error!
ST_BAKFSC=Backup %S:
ST_BAKEND=End Backup...
ST_NOBAKFSC=FSC Backup Failed!#Click Refresh button and try again.
ST_FSCVIN=Get FSC VIN...
ST_WRCODE=Write activation code...
ST_LOWCODE=The Activation code lower than map version
ST_WRCODEERR=Write Activation code failed,pls try again...
ST_CPSERR=VIN format error, can not continue.
ST_STEP_CUR=Current:%S-%d-%d-%d
ST_STEP_LAS=Last:%S-%d-%d-%d
ST_STEP_SHI=Shipment:%S-%d-%d-%d
ST_SET_EXT_DS=Set Extended Diagnostic Session...
ST_Lese_FTP=Lese Flash Timing Parameter...
ST_Lese_ADS=Lese Active Diagnostic Session...
ST_SDS=Set Default Session...
ST_SRESET=Sending restart command...
ST_WAITRE=Waiting for the modules to restart...
ST_TESTM=Final mission testing...
ST_MISSOK=Mission completed...
ST_MISSTER=Mission Terminated...
ST_NOP=Clear execution state...
ST_REDY=Prepare vehicle coding tasks...
ST_SVK=Getting SVK...
ST_SAR=Security access request...
ST_ACCVER=Access verification...
ST_ACCVERERR=Access verification failed!(%S)
ST_SVF_MT=Signature verification failed(%S), Mission termination...
ST_TRYLATER=Unable to secure access, please try again later ...
ST_FTRSA=Request secure access failed...
ST_WRITING=Writing...
ST_WCPS=Writing CPS...
ST_VWD=Verify written data...
ST_CHECKSI=Verify the signature...
ST_GET_CAFD=Get [%S] CAFD information...
ST_CHECK_V=[%S]Detected voltage:%S V.
ST_CHECKV=Detecting car voltage...
ST_CHECKVERR=Unable to detect voltage information,#Ensure the car voltage sufficient and stable!#Continue to write it?
ST_V_LOW=Detection voltage is almost critical point,#In order to ensure safe when writing,#Please write after charging.
ST_CAS=The current code for a starting system control unit (%S).Please turn off the engine continues ...
ST_PROGCOUNT=ECU(%S)Programming Counter:%D Max Value:%D...
ST_NOINFO=This information is not recorded..
ST_MODEDATE=ECU(%S)Manufacturing Date:%S-%S-%S
ST_CLEAR_DTC=ECU:%S DTC Cleared...
ST_SVFAIL=Signature verification failed, mission failed.
ST_KEYFAIL=Key verification failed, abort...
ST_WRITEFAIL=Write failed!#click the Restore button to restore...
ST_NOTRECVCOD=The ECU cannot receive coding tasks,#Please try again later ...
ST_TIMEINVA=Time-domain state is invalid,#please try again later...
ST_WRITETIMEOUT=Response Timeout, please try again...
ST_VIN_FAIL=Check failed [%S] ...
ST_DESKTOP=Software located on the desktop.#Because the software will generate the necessary directories and files,#And automatically backs up the car's original data,#Recommend copying the software in a dedicated directory.#Still run the program now?
ST_SCAN_CAR=Detecting car...
ST_SCANED=Please connect after detect car ...
ST_RELINK=To reconnect, disconnect the current connection first.
ST_LINKING=Connecting ...
ST_LINKSER=Connecting service ...
ST_GETVIN=Getting VIN...
ST_HAND=Handshaking...
ST_UNLINK=Disconnected...
ST_COM_WAIT=Previous command is not finished, please wait ...
ST_GETECU=Getting car's ECUs...
ST_UPDATE=Part of the data need update, please contact me...
ST_SELECU=Please choose an ECU to Lese ...
ST_NOSUP=Does not support this module...
ST_CODINST=Coded the instrument panel data, maintenance, time and other information will be lost!#Still code it?
ST_NODATA=The current version is no this ECU data ...
ST_UPDATE=Incomplete data, please upgrade...
ST_LeseCODE=Leseing...
ST_NEEDUP=Incorrect data, pls update data ...
ST_DATERR=Incorrect data, could not be completed ...
ST_CHECK=Data integrity checking...
ST_CHECKERR=Data validation fails, do not write to...
ST_WRIT=Changes take effect after writing.
ST_LeseFIRST=Please Lese first...
ST_AUTOBAK=Automatic backup data...
ST_BACKUP=Backup data...
ST_OVERBAK=Backup alLesey exists, whether to overwrite backup?
ST_BAKERR=Critical error:#Unable to backup data, the backup operation is very important!#Check and eliminate the cause of this error!
ST_INPUTERR=Incorrect value is entered! Modification fails...
ST_OUTRANGE=Value out range, it has been intercepted...
ST_NOKEY=Get key data error!(%S)
ST_BAKCON=Confirm the selected ECU return to backup status?
ST_CLEARDTC=Confirm Clear to selected ECU's DTC?
ST_ALLDTC=Confirm Clear all DTC?
ST_CONRESTART=Confirm restart to selected ECU?
ST_SELAECU=Please choose an ECU to restore...
ST_BACKMODIED=Backup file has been modified, cannot be restored ...
ST_NOSAVE=Nothing to save....
ST_NOCOMP=Not completed, so stay tuned ....^_^
ST_CODIHKA=Some models car can not turn off air conditioning when after code.#This is completely normal phenomenon, #it can be restored after running for some times.
ST_DOWNFAIL=Unable to download, possible causes:#1. Network unreachable.#2. The information is not available in the selected language.
ST_UPCOUNT=Updated Keywords: %D
ST_POSSAVE=Keywords change the location need to resave.#Whether or not to save?
ST_DELKEY=Confirm to delete the currently selected keyword?
ST_KEYEMPT=Current custom keywords is empty, now connect to the network and update?
ST_ECUCHANG=ECU list has changed, please re-Lese the coding...