;********Special symbols:  (Please keep the format integrity.)********
;  #-as a newline, In the middle of the string,
;  !-Displayed in red at the CodingList,First char of the string
;  ,-Separator
;  &-Shortcuts delimiter
;  %S,%D-Replace strings and numbers
;  |-Status Bar hint
;*********************************************************************

;****************************Language*********************************
Lang=Italiano
;*********************************************************************
Translate= bmwretrofit.it
;*****************Translator copyright information********************
;Be displayed in the application
Copyright=Benvenuto ...#Questa applicazione e' gratuita, non dovete pagare nulla. #Mia email: snzdl555@gmail.com #Traduzione by BMWRETROFIT.IT   
;*********************************************************************

;***************************Application*******************************
[APP]
BT_TOOLS=&Tools
BT_FILTER=&Filtro
BT_CANCEL=&Cancella
BT_OK=&OK
BT_Close=&Chiudi
BT_SAVE=&Salva
BT_ADD=&Aggiungi
BT_INSERT=&Inserisci
BT_Copy=&Copia in memoria
BT_HIDELIST=Lista codifiche
BT_SCANCAR=&1.Identifica
BT_SCANCAR_HINT=|Identifica informazioni vettura alla connessione.
BT_LINKCAR=&2.Connetti
BT_LINKCAR_HINT=|Connessione alla vettura.
BT_UNLINK=&Disconn.
BT_UNLINK_HINT=|Disconnesso
BT_LINKNAT=&Connetti
BT_LINKNAT_HINT=|Connessione con ICOM o NAT.
BT_READECUS=&3.Leggi ECU list
BT_READECUS_HINT=|Leggi tutte informazioni dei moduli vettura.
BT_SAVEECUS=&Salva
BT_SAVEECUS_HINT=|Salva le info modulo in file di testo.
BT_ABOUT=&About
BT_ABOUT_HINT=|About this app.
BT_OPTION=&Opzioni
BT_OPTION_HINT=|Setting Options.
BT_QUIT=&Uscita
BT_QUIT_HINT=Esci dall'Applicazione
BT_READ=&4.Leggi
BT_READ_HINT=|Leggi dati dal modulo selezionato.
BT_WRITE=&5.Scrivi
BT_WRITE_HINT=|Invia codifica - write-car.
BT_BACK=&Backup
BT_BACK_HINT=|backup dei dati originali (App eseguira' il backup automaticamente).
BT_RECOVERY=&Ripristina
BT_RECOVERY=|Ripristina Codifica da backup.
BT_LOADFSC=&Apri FSC
BT_LOADFSC_HINT=|Carica file FSC , il formato di file può essere binario o esadecimale o XML.
BT_SAVEFSC=&Salva FSC
BT_SAVEFSC_HINT=|L'FSC nella casella di modifica salvarlo come un file  binario o esadecimale.
BT_REFRESH=&Aggiorna
BT_REFRESH_HINT=|Rileggere l'elenco FSC nel Headunit.
BT_GETFSC=&Leggi FSC
BT_GETFSC_HINT=|Prendi FSC selezionata da headunit.
BT_BAKFSC=&Backup Tutti FSC
BT_BAKFSC_HINT=|Backup di tutti gli FSC dell' Headunit.
BT_GEN=&Genera FSC
BT_PUTFSC=&scrivi in auto
BT_PUTFSC_HINT=|Put the activation code to headunit. when upgrade map, do not need to be input manually.
BT_GETFMAP=Ottieni da &mappa
BT_GETFMAP_HINT=|Get the country code and version number from the map file.
BT_GETFXML=Ottieni da &lookup
BT_FILTER_HINT=| Show only configuration file (KeyList.ini) keywords.
BT_SEARCH_HINT=| Search specified keyword.
BT_CUSTOM=&Custom
BT_DOWNLOAD=&Download
BT_DOWNNOW=&Download Now
BT_CLEARANDRE=Clear all and &re-read

LB_Country=Country:
LB_VERCODE=VerCode:
LB_VIN=VIN:
LB_WARNING=WARNING:
LB_FSCNOTE=Note:Fsc Generator non e' una mia app, ringrazio l'autore originale!
LB_WAR_TIP=Scrittura fallita causa : modulo non risponde o non funziona!#Controllare rigorosamente le seguenti operazioni:#  1, La vettura deve essere ACC ON.#  2, Spegnere l'aria condizionata e altri moduli ad alta potenza.#  3, Avviare la macchina, ma deve essere spenta quando si scrive in modulo CAS / BODY.#  4, Non utilizzare la macchina durante la scrittura.#  5, Assicurarsi che la connessione non sara' interrotto.#  6, Se dovesse fallire, si prega di fare clic sul pulsante di ripristino per riparare.
LB_BAKNOTE=    Se è la prima lettura, per ragioni di sicurezza, App effettua un backup di sicurezza.#I file di backup vengono memorizzati nella cartella dell'app, la sottodirectory è denominata con VIN.#Assicurarsi di mantenere questa directory e file,##    Clicca "Ripristina" per ripristinare i dati di backup, Se si ha bisogno.
LB_IP=Scan IP:
LB_LINKPORT=Link Port:
LB_SCANPORT=Scan Port:
LB_BAKTIT=Seleziona File per ripristino:
LB_HIDELISTTIP=varie opzioni dell' auto.
LB_SCANING=Rilevo la Vettura, attendere prego ....
LB_SCANTIP=1.La vettura deve essere ACC ON.#2.Indirizzo IP impostato su automatico DHCP.#3.Il Firewall non blocca l'accesso alla rete.
LB_ENTER=Invio#Per Confermare
LB_IMPORTANT=IMPORTANTE:
LB_CDATE=Data creazione:
LB_ICOM=    Ottieni IP e porta dell' ICOM (di solito: 169.254.92.38:50160),e inseriscilo qui sotto.
LB_WFAIL=Operazione di scrittura anomala, missione fallita, si consiglia di riprovare o ripristinare un backup, se non non si riesce, il modulo corrente potrebbe non funzionare correttamente. (Se dopo più tentativi non si riesce, si raccomandata l'uso di E-Sys per lacorrezione.)
LB_KEYNAME=Keyword:
LB_DES=Descrizione:
LB_EXDES=Dettagli:
LB_TYPE=Tipo:
LB_ITEM=Lista items:
LB_LANG=Seleziona una lingua:
LB_TIMING=Write timing fine-tuning(Unit:ms):
LB_TIMETIP=If repeatedly write error, please appropriate to increase this value.
LB_DOWNTIP=Current module (ECU) no custom item, click the "Custom" button and download the custom data and try again. You can also define your own keywords by custom keywords editor, coding easier and faster.
LB_DOWNDTC=Fault code documentation is empty, Click on the download button below, You can view the corresponding description text.

RG_PROC_CAP=Choose a processing mode
RG_PROC_ITEMS="try again","Restore a backup","Termination task (module may not work!)"
RG_DOWNTYPE_CAP=Download mode:
RG_DOWNTYPE_ITEMS="Add Update","Overwrite existing"
RG_LANG_CAP=Choose a language:

MI_ECU_DATE=Leggi Data Produzione ECU 
MI_ECU_PROG=Leggi Programming Counter
MI_ECU_VOLT=Rileva voltaggio
MI_CAR_STEP=Livello Integrazione
MI_FSCTOOLS=FSC Tools
MI_ECU_CPS=Leggi CPS
MI_ECU_SVK1=Leggi Current SVK
MI_ECU_SVK2=Leggi System Supplier SVK
MI_ECU_SVK3=Leggi Plant SVK
MI_SVK_BAK1=Leggi Backup SVK 1
MI_SVK_BAK2=Leggi Backup SVK 2
MI_SVK_BAK3=Leggi Backup SVK 3
MI_ECU_DTC=Cancella DTC selezionati in ECU
MI_ALL_DTC=Cancella tutti DTC
MI_ECU_RE=Restart ECU
MI_GEARBOX=Ripristina valori di adattamento cambio (abitudini di guida in memoria)
MI_GETGEARBOX=Vedi valori di adattamento cambio
MI_DATETIME=Sincronizza la data e l'ora per il Kombi
MI_PHONENUM=Headunit preset phone numbers
MI_BTNAME=Bluetooth device name
MI_READDTC=Read DTC

CH_NONEXT=Non mostrare più
CH_AutoDetect=Scansione automatica dopo l'avvio.
CH_AutoLink=Connetti automaticamente all'auto.
CH_AutoRead=Leggi automaticamente la lista ECU.
CH_AUTOSETTIME=sincronizza KOMBI dopo la codifica 
CH_RESETFIRST=Restart the module and then execute

GB_CAROPTION=Car
GB_SYSOPTION=System
GB_ECUS=ECUs
GB_CODE=Coding
GB_EDITKEY=Edit Keyword
GB_KEYLIST=Custom keyword list

CB_TYPE=Default,"Digital editing box","Custom list"

PA_WAIT=In comunicazione, attendere ...

LV_BAK=Backup Files,Backup Date
LV_FSC=Number,Index,Status
LV_KEYS=Description,Keyword,Items

TS_Custom=Custom
TS_Normal=Normale

TB_CUSTOM=Save,Add,Remove,Edit,"Move left","Move Right","Move up","Move Down",Notepad,Download

ListView_HINT=Colore blue possibile codificare, se ha colore rosso, si prega di contattarmi per l'aggiornamento.
HideView_HINT=Set it as required and written to the car go into effect.

ST_TIMEOUT=Timeout!
ST_GETPRESSURES=Get Clutch fill pressures...
ST_GETFILLTIME=Get Rapid fill times...
ST_ADAP=Clutch fill pressures:#   Clutch A: %D.0 mbar#   Clutch B: %D.0 mbar#   Clutch C: %D.0 mbar#   Clutch D: %D.0 mbar#   Clutch E: %D.0 mbar##Rapid fill times:#   Clutch A: %D.0 ms#   Clutch B: %D.0 ms#   Clutch C: %D.0 ms#   Clutch D: %D.0 ms#   Clutch E: %D.0 ms  
ST_GENFAIL=Calcolo fallito!
ST_SELTYPE=Si prega di selezionare il tipo di unita' principale prima.
ST_MAPINFO=Country Code:%S Ver Code:%S
ST_FSCEXE=Non posso aprire il generatore, il generatore non esiste.
ST_FORMATERR=Formato file errato!
ST_BAKFSC=Backup %S:
ST_BAKEND=Fine Backup...
ST_NOBAKFSC=FSC Backup Fallito!#Clicca il pulsante aggiorna e riprova.
ST_FSCVIN=Get FSC VIN...
ST_WRCODE=Scrivi codice di attivazione...
ST_LOWCODE=Il codice di attivazione mappa e' inferiore alla versione
ST_WRCODEERR=Scrittura codice di attivazione non riuscita, pls riprovare...
ST_CPSERR=VIN errore di formato, non si può continuare.
ST_STEP_CUR=Current:%S-%d-%d-%d
ST_STEP_LAS=Last:%S-%d-%d-%d
ST_STEP_SHI=Shipment:%S-%d-%d-%d
ST_SET_EXT_DS=Set esteso di sessione diagnostica...
ST_READ_FTP=Leggi Parametri Flash Timing...
ST_READ_ADS=Leggi sessione diagnostica attiva...
ST_SDS=Imposta sessione predefinita...
ST_SRESET=Invio comando restart...
ST_WAITRE=Attesa per il riavvio del modulo...
ST_TESTM=Missione Finale di testing...
ST_MISSOK=Missione completa...
ST_MISSTER=Missione Terminata...
ST_NOP=Chiaro stato di esecuzione...
ST_REDY=Preparare attivita' di codifica del veicolo ...
ST_SVK=Ottieni SVK...
ST_SAR=Richiesta sicurezza di accesso...
ST_ACCVER=verifica di accesso...
ST_ACCVERERR=Verifica di accesso non riuscita!(%S)
ST_SVF_MT=Verifica della firma fallita(%S), Missione terminata...
ST_TRYLATER=non in grado di garantire l'accesso, si prega di riprovare più tardi ...
ST_FTRSA=Richiesta accesso sicuro fallita...
ST_WRITING=Scrittura...
ST_WCPS=Scrittura CPS...
ST_VWD=Verifica dati scritti...
ST_CHECKSI=Verificare la firma...
ST_GET_CAFD=Get [%S] InformazioniCAFD...
ST_CHECK_V=[%S] Tensione Rilevata:%S V.
ST_CHECKV=Rilevamento tensione...
ST_CHECKVERR=Impossibile rilevare informazioni sulla tensione,#Assicurarsi che la tensione dell' auto sia sufficiente e stabile!#Continuare a scrivere?
ST_V_LOW=Il rilevamento della tensione, è quasi critico,#Al fine di garantire sicurezza durante la scrittura,#Si prega di scrivere dopo la ricarica.
ST_CAS=Il codice corrente, per avviamento un'unita' di controllo sistema (%S).Si prega di spegnere il motore per continuare ...
ST_PROGCOUNT=ECU(%S)Contatore programmazione:%D Max Value:%D...
ST_NOINFO=Queste informazioni non vengono registrate..
ST_MODEDATE=ECU(%S)Manufacturing Date:%S-%S-%S
ST_CLEAR_DTC=ECU:%S DTC Cancellati...
ST_SVFAIL=Verifica della firma non riuscita, missione fallita.
ST_KEYFAIL=Verifica Key fallita, Annullo...
ST_WRITEFAIL=Scrittura Fallita!#fare clic sul pulsante Ripristina per ripristinare...
ST_NOTRECVCOD=La centralina non può ricevere codifica,#Riprova piu' tardi ...
ST_TIMEINVA=Time-domain stato non valido,#Riprova piu' tardi...
ST_WRITETIMEOUT=Risposta Timeout , riprova...
ST_VIN_FAIL=Controllo fallito [%S] ...
ST_DESKTOP=Software sul desktop.#Poiché il software genera le directory e i file necessari,#E esegue automaticamente il backup dei dati originali della vettura,#Si consiglia la copia del software in una directory dedicata.#Rieseguire il programma ora?
ST_SCAN_CAR=Rileva auto...
ST_SCANED=connettersi dopo il rilevamento auto...
ST_RELINK=Per ricollegare, prima disconnettere la connessione corrente.
ST_LINKING=Connesso...
ST_LINKSER=Collegamento al servizio...
ST_GETVIN=Ottieni VIN...
ST_HAND=in attesa di connessione...
ST_UNLINK=Disconnesso...
ST_COM_WAIT=Comando precedente non è terminato, si prega di attendere ...
ST_GETECU=Leggi ECU dell' auto...
ST_UPDATE=Parte dei dati hanno bisogno di aggiornamento, si prega di contattarmi...
ST_SELECU=Scegliere una ECU da leggere ...
ST_NOSUP=Non supporta questo modulo...
ST_CODINST=Codificando il Kombi, la manutenzione, l'ora e altre informazioni andranno perse!#codifico?
ST_NODATA=La versione attuale non comprende questa ECU ...
ST_UPDATE=Dati incompleti, Aggiorna...
ST_READCODE=Sto leggendo...
ST_NEEDUP=Dati incorretti, pls aggiorna dati ...
ST_DATERR=Dati non corretti, impossibile completare ...
ST_CHECK=Controllo dell'integrita' dei dati...
ST_CHECKERR=La convalida dei dati non riuscita, scrittura fattita...
ST_WRIT=Le modifiche avranno effetto dopo la scrittura.
ST_READFIRST=Prima leggi...
ST_AUTOBAK=Backup Automatico dei dati...
ST_BACKUP=Backup dei dati...
STST_OVERBAK=Backup esiste gia', vuoi sovrascrivere il backup?
ST_BAKERR=Errore critico:#Incapace di eseguire backup, l'operazione di backup è molto importante!#Controllare ed eliminare la causa di questo errore!
ST_INPUTERR=Valore inserito non corretto! modifica fallita...
ST_OUTRANGE=Valore fuori range,..interrotto...
ST_NOKEY=Leggi dati errore!(%S)
ST_BAKCON=Confermare il ritorno allo stato di backup dell'ECU?
ST_CLEARDTC=Confermi la cancellazione dei DTC dell'ECU ?
ST_ALLDTC=Confermi la cancellazione di tutti i DTC?
ST_CONRESTART=Confermi il riavvio dell'ECU selezionata?
ST_SELAECU=Scegliere una ECU da ripristinare...
ST_BACKMODIED=Il file di backup è stato modificato, non può essere ripristinato ...
ST_NOSAVE=Niente da salvare....
ST_NOCOMP=Non completato, quindi rimanete sintonizzati ....^_^
ST_CODIHKA=Alcuni modelli di auto non possono spegnere l'aria condizionata dopo la codifica.#Questo è un fenomeno normale,#essa può essere ripristinata dopo l'esecuzione alcune volte
ST_DOWNFAIL=download non possibile, possibile cause:#1. Rete irraggiungibile.#2. Informazioni non disponibili nella lingua selezionata
ST_UPCOUNT=Aggiornamento Keywords: %D
ST_POSSAVE=Posizione Keywords cambiata,necessario salvare.#salvo o non salvo?
ST_DELKEY=Confermi la cancellazione della keyword selezionata?
ST_KEYEMPT=La keywords corrente è vuota, Vai su "Custom" editor e scarica per utilizzarla!
ST_ECUCHANG=ECU list has changed, please re-read the coding...