[ICM]
00=电子限速,关闭,开启

[FRM/BODY]
;12F
00=自动启停记忆上次操作状态,开启,关闭
01=默认关闭自动启停,关闭,开启
02=开门终止升窗,开启,关闭
03=开门终止升窗,开启,关闭
04=转向灯次数
05=迎宾灯亮时打开左雾灯,不激活,软开,硬开
06=迎宾灯亮时打开右雾灯,不激活,软开,硬开
07=紧急刹车开启双闪灯,关闭,开启
08=氛围灯亮度调整
09=锁车后内部灯光保持时间
10=锁车后内部灯光保持时间
11=解锁后内部灯光保持时间
12=解锁后内部灯光保持时间
13=倒车副驾后视镜下翻角度
14=开启大灯清洗,开启,关闭
15=大灯清洗间隔,1次,5次,10次
16=每次大灯清洗次数
17=熄火后主驾驶门开自动关闭收音机和音乐,开启,关闭
18=踩刹车启动,开启,关闭
19=急刹时候高位刹车灯闪烁,关闭,flaechenvergroesserung,刹车灯闪烁
20=急刹高位刹车灯闪烁灵敏度,ECE,US,ECE_M_Sport
21=急刹高位刹车灯闪烁灵敏度,ECE,US
22=折叠后视镜延迟时间:
23=急刹高位刹车灯闪烁功能灵敏度,ECE,US,ECE_M_Sport
24=急刹高位刹车灯闪烁功能灵敏度,ECE,US
25=个性双跳灯
26=远光灯助手默认开启,关闭,开启
27=门把手LED倒车时亮起,开启,关闭
28=急刹高位刹车灯闪烁灵敏度,ECE,US
29=熄火后开门关闭主机,开启,关闭
30=折叠后视镜延迟时间:
31=1雾灯弯道辅助照明:
32=2自动前照灯调平系统(AHL),关闭,开启
33=2转弯照明,关闭,开启
34=2左弯道灯,关闭,开启
35=2右弯道灯,关闭,开启
36=2控制信号映射输出(左),开启,FL_L,关闭
37=0控制信号映射输出(右),开启,FL_R,关闭
EX03=关闭后升窗操作不会因车门打开而终止
EX04=最大数值7
EX20=根据减速度
EX21=根据闸流量
EX22=单位100ms,0为无延迟(一键折叠后视镜)
EX23=根据减速度来判断
EX24=根据闸流量来判断
EX26=开启后当大灯亮起时自动打开远光助手
EX28=根据闸流量
EX30=单位100ms,0为无延迟(一键折叠后视镜)
EX33=2前提条件:开启AHL
[FZD]
00=上锁提示音音量
01=上锁提示音自动音量,开启,关闭
02=蜂鸣器声音频率
03=蜂鸣器发声延时
EX01=开启后20:00到8:00时间段声音将变小。
[CAS]
00=自动启停记住上次状态,开启,关闭
01=自动启停默认关闭状态,开启,关闭
02=熄火后开门关闭主机,开启,关闭
[KOMBI]
;760  69
00=GPS时间同步,开启,关闭
01=仪表瞬时油耗标尺,20L/100/km,30L/100km
02=仪表盘白天背景颜色,橙色,灰色
03=仪表盘夜晚背景颜色,橙色,灰色
04=仪表白天亮度值:
05=仪表晚上亮度值:
06=HUD显示娱乐信息,开启,关闭
07=HUD显示电话信息,开启,关闭
08=HUD显示电话薄信息,开启,关闭
09=HUD显示语音命令信息,开启,关闭
10=HUD显示转向灯,开启,关闭
11=数字车速,开启,关闭
12=开车后旅程电脑复位延迟(小时)
13=HUD开机画面时间
14=开门提醒,开启,关闭
15=燃油报警公里数:
16=第二次燃油报警公里数:
17=根据转速曲线修正车速,开启,关闭
18=HUD显示转向灯,开启,关闭
19=HUD指示灯,开启,关闭
20=仪表LOGO索引号:
21=启用罗盘图,开启,关闭
22=启用数字里程表,不显示,kmh_mph,mph_kmh,mph_mph,不显示MPH,不显示KMH
EX11=用转向杆上的BC按钮调出
EX12=设置为0时,每次启动旅程电脑即刻复位
EX17=关闭后将显示实际车速
EX20=仪表中如无相关图像则显示不出
EX21=液晶仪表适用
EX22=后两个选项仅005_000_056以后版本可用
[HKL]
00=A柱开关操作电尾门,关闭,开启
01=通过钥匙按钮终止并反向操作电尾门,关闭,开启
02=遥控按钮与A柱按钮匹配,关闭,开启
03=A柱按钮可开也可关电尾门,关闭,开启
04=钥匙按钮可关闭尾门,关闭,开启
[IHKA]
00=空调开关记忆上次状态,开启,关闭
01=空调开关记忆上次状态,关闭,开启
02=空调循环记忆上次状态,开启,关闭
03=空调循环记忆上次状态,关闭,开启
[ACSM]
;9C 9D 147
00=安全带报警声时长
01=乘客安全带报警,开启,关闭
02=驾驶员安全带报警,开启,关闭
03=驾驶员安全带状态显示,开启,关闭
04=乘客安全带状态显示,开启,关闭
05=驾驶员安全带打开提醒,开启,关闭
06=乘客安全带打开提醒,开启,关闭
07=最初的安全带警告,开启,关闭
EX00=单位:秒,响一声大概2-3秒
[CIC/NBT]
00=上锁/解锁时的提示音选项,开启,关闭
01=1行驶中看视频操作导航
02=2解除导航、视频锁定的速度值:
03=0激活导航、视频锁定的速度值:
04=显示法律免责声明延时:
05=倒车影像免责声明延时:
06=夜视影像免责声明延时:
07=版本查看菜单,开启,关闭
08=显示发动机功率及扭矩,开启,关闭
09=蓝牙来电声为手机铃声,开启,关闭
10=导航显示加油站提醒,开启,关闭
11=可USB导入地图编码,开启,关闭
12=导航下增加位置菜单,关闭,开启
13=导航兴趣点在线搜索,browser,nativ
14=1从USB读取视频播放,关闭,第1USB,第2USB,全部USB
15=2视频解码器Xvid,关闭,开启
16=0VCD和SVCD的视频支持,关闭,开启
17=视频文件保存到内部储存器后播放,关闭,开启
18=导航路线预览功能,开启,关闭
19=导航线路预览按钮,关闭,开启
20=导航语音男女声,开启,关闭
21=屏幕显示方式,窄屏,宽屏,flap,schmales_flap
22=倒车模拟图像显示方式,竖向,横向
23=日间行车灯(天使眼)选项,关闭,开启,标准
24=灯光设置中显示氛围灯调整,关闭,开启
25=禁用UPnP/WLAN音频,开启,关闭
26=禁用UPnP/WLAN视频,开启,关闭
27=从WLAN设备中获取视频流,关闭,开启
28=切换Wi-Fi开关,开启,关闭
29=切换WLAN连接模式,AP,客户端,全部,WIFI直连
30=WIFI连接强度,车内,车外
31=菜单中增加M数字转速显示,开启,关闭
32=M-HUD,开启,关闭
33=主机启动画面,默认,M,ALPINA,"BMW I","bmw i",天使,跟默认一样,小BMW,橙色格栅BMW,圣诞
34=设置中显示HUD显示转向灯选项,开启,关闭
35=油位菜单,开启,关闭
36=放手刹终止视频,关闭,开启
37=音量提示条,显示,不显示
38=音量条淡入淡出提前结束,开启,关闭
39=音量条低优先级显示,开启,关闭
40=1控制器可触摸操作,关闭,开启
41=2互动地图中可用触摸,开启,关闭
42=2触摸用于拼写,开启,关闭
43=2触摸用于浏览器,开启,关闭
44=0高速锁定触摸操作,开启,关闭
45=电子罗盘,开启,关闭
46=激活菜单力矩和xDrive状态,开启,关闭
47=3D地图滚动,开启,关闭
48=1数字胎压监测系统,开启,关闭
49=0数字胎压监测-车辆安全性,开启,关闭
50=HUD抬头显示,已安装,未安装
51=显示B&&O音效菜单,kein_menue,keine_insz,nur_lichtinsz,volle_insz
52=在音效菜单中显示Logic7_Logo,开启,关闭
53=EQ数据必须加载的定义,stereo,hifi,tophifi,individual_sound,hk_surroundsound,highpremium,hifi_system_harmankardon
54=1蓝牙音乐
55=0苹果设备蓝牙音频流,开启,关闭
56=2蓝牙音频流控制器,开启,关闭
57=2蓝牙音频流控制器,开启,关闭
58=M配色方案,开启,关闭

EX00=需在设置-车门锁中打勾后使用
EX01=将所有设为255
EX02=设255时将不锁定视频和导航(注意行车安全)
EX03=设255时将不锁定视频和导航(注意行车安全)
EX04=开机时的确认画面(0不显示)
EX05=倒车时的法律免责声明(0不显示)
EX06=夜视时的免责提示(0不显示)
EX07=设置里右拨iDriver查看
EX08=可在IDriver中查看
EX09=此功能仅对于iPhone手机有效。
EX14=选择哪个USB口用来播放视频
EX15=USB播放视频支持MP4
EX16=USB播放视频支持MPEG
EX23=在设置中显示天使眼的开关
EX25=WIFI播放音乐(部分车型已被阉割)
EX26=WIFI播放视频(部分车型已被阉割)
EX27=(部分车型已被阉割)
EX28=(部分车型已被阉割)
EX32=需另外调整HUD中相关选项
EX33=未统计标识,希望有统计出的提供一份给我!^_^
EX34=需修改KOMBI里相应选项后使用
EX38=当有其他操作时
EX39=开启后在有其他警告信息时低优先显示
EX46=显示罗盘需打开
EX48=!无数字型胎压系统不要打开
EX50=激活加装HUD
EX56=A2DP & AVRCP 1.3
EX57=AVRCP1.4含浏览

[CMB_MEDIA]
00=语音识别,开启,关闭
01=使用手机电话铃声,关闭,启用
02=来电铃声选择,RING_TONE1,RING_TONE2,RING_TONE3
EX01=仅支持IPHONE
